import { useEffect, useMemo, useRef, useState, type FormEvent, type ReactNode } from "react";
import { AppShell, Avatar, Button, DataSheet, DataSheetCell, DataSheetHeader, DataSheetRow, IconButton, Pagination, SearchField, StatusChip, Tooltip } from "@paryatech/design-system";
import { buildNavGroups } from "./nav";
import { IconArrowIn, IconArrowOut, IconBank, IconBell, IconCalendar, IconCheck, IconChevronRight, IconClose, IconDownload, IconFinance, IconHelp, IconPlus, IconReceipt, IconWarning } from "./icons";
import { ACCOUNTS, ACTIVITY, CUSTOMER_ADVANCE, EXPENSES, FORECAST, OBLIGATIONS, REFUND, REVIEW_DATE, TRANSACTIONS, bookingProjectedMargin, dueLabel, forecastClosing, forecastMinimum, formatDate, formatDateTime, formatMoney, outstanding, recordedCash, remaining, statementClosing, statementDifference, statusTone, unmatchedStatementRow, unexplainedAfterVisibleRow, type ActivityEvent, type Expense, type MoneyRecord, type Obligation, type PageId, type Tone } from "./financeModel";
import "./App.css";
import "./FinanceApp.css";

const PAGE_LABELS: Record<PageId, string> = { overview: "Overview", receivables: "Receivables", payables: "Payables", transactions: "Transactions", expenses: "Expenses", bank: "Bank & cash", reports: "Reports", controls: "Approvals & closing" };
const PAGE_DESCRIPTIONS: Record<PageId, string> = { overview: "Track collections, payments and agency expenses.", receivables: "Customer amounts, receipts and credits.", payables: "Supplier commitments, bills and payments.", transactions: "Money movements and their verification trail.", expenses: "Agency costs and staff reimbursements.", bank: "Accounts, statements and reconciliation.", reports: "Financial views with their source records.", controls: "Approvals, exceptions and period review." };
type Detail = { type: "obligation"; id: string } | { type: "transaction"; id: string } | { type: "expense"; id: string } | { type: "activity"; id: string } | { type: "statement"; id: string } | { type: "advance"; id: string };
type RecordType = "Receipt" | "Supplier payment" | "Agency payment" | "Account transfer";

function Status({ children, tone }: { children: ReactNode; tone: Tone }) { return <StatusChip tone={tone}>{children}</StatusChip>; }
function NumberCell({ value, direction }: { value: number; direction?: "in" | "out" | "neutral" }) { return <span className={"money" + (direction === "in" ? " money--in" : direction === "out" ? " money--out" : "")}>{direction === "in" ? "+" : direction === "out" ? "−" : ""}{formatMoney(value)}</span>; }
function downloadCsv(filename: string, rows: Array<Array<string | number>>) {
  const csv = rows.map((row) => row.map((cell) => '"' + String(cell).replaceAll('"', '""') + '"').join(",")).join("\n");
  const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" }));
  const link = document.createElement("a"); link.href = url; link.download = filename; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url);
}
function Summary({ items }: { items: Array<{ label: string; value: string; note?: string; onClick?: () => void }> }) {
  return <div className="finance-summary">{items.map((item) => <button type="button" key={item.label} className="finance-summary__item" onClick={item.onClick} disabled={!item.onClick}><span>{item.label}</span><strong>{item.value}</strong>{item.note ? <small>{item.note}</small> : null}</button>)}</div>;
}
function ViewTabs({ items, value, onChange }: { items: string[]; value: string; onChange: (value: string) => void }) {
  return <div className="view-tabs" role="tablist">{items.map((item) => <button role="tab" aria-selected={item === value} className={item === value ? "is-selected" : ""} key={item} type="button" onClick={() => onChange(item)}>{item}</button>)}</div>;
}
function Empty({ message }: { message: string }) { return <div className="finance-empty">{message}</div>; }
function activityTime(value: string) { return new Intl.DateTimeFormat("en-GB", { hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(value)); }
function activityInitials(name: string) { return name.split(" ").map((part) => part[0]).slice(0, 2).join("").toUpperCase(); }
function activityRole(name: string) { return name === "Vrushabh Jain" ? "Owner" : name === "Finance reviewer" ? "Reviewer" : "Staff member"; }
function ActivityDate({ row }: { row: ActivityEvent }) { return <div className="finance-activity-date"><span><IconCalendar size={14} />{formatDate(row.occurredAt)}</span><small title={`Occurred ${formatDateTime(row.occurredAt)} · Recorded ${formatDateTime(row.recordedAt)}`}>{activityTime(row.occurredAt)} · recorded {row.recordedAt.slice(0, 10) === row.occurredAt.slice(0, 10) ? "" : `${formatDate(row.recordedAt)} `}{activityTime(row.recordedAt)}</small></div>; }
function ActivityMember({ name }: { name: string }) { return <div className="finance-activity-member"><Avatar size={28} tone={name === "Vrushabh Jain" ? "default" : "pink"}>{activityInitials(name)}</Avatar><span><strong>{name}</strong><small>{activityRole(name)}</small></span></div>; }

function ObligationSheet({ rows, onOpen, mode, receiptDecision = "pending" }: { rows: Obligation[]; onOpen: (detail: Detail) => void; mode: "customer" | "payable" | "attention"; receiptDecision?: "pending" | "verified" | "rejected" }) {
  return <div className="finance-table"><DataSheet className="finance-obligation-sheet" aria-label={mode === "customer" ? "Customer amounts to collect" : mode === "attention" ? "Finance work needing attention" : "Outgoing obligations"}>
    <DataSheetHeader><DataSheetCell>Party / booking</DataSheetCell><DataSheetCell>Due item / review</DataSheetCell><DataSheetCell>Remaining</DataSheetCell><DataSheetCell>Due</DataSheetCell><DataSheetCell>Next action</DataSheetCell></DataSheetHeader>
    {rows.map((row) => <DataSheetRow key={row.id}>
      <DataSheetCell><button type="button" className="finance-primary-link" onClick={() => onOpen({ type: "obligation", id: row.id })}>{row.party}</button><small className="cell-sub">{row.booking}</small></DataSheetCell>
      <DataSheetCell><span className="cell-main">{row.item}</span><button className="cell-sub cell-link" type="button" onClick={() => onOpen({ type: "obligation", id: row.id })}>{row.document}</button><span className="cell-sub">{row.kind === "customer" && row.id === "COL-00029" ? <Status tone={receiptDecision === "rejected" ? "blocked" : receiptDecision === "verified" ? "done" : "open"}>{receiptDecision === "rejected" ? "Proof rejected" : receiptDecision === "verified" ? "Verified" : "Awaiting verification"}</Status> : <Status tone={row.documentState === "Issued" ? "done" : "open"}>{row.documentState}</Status>}</span></DataSheetCell>
      <DataSheetCell><NumberCell value={remaining(row)} /></DataSheetCell>
      <DataSheetCell><span className="cell-main">{formatDate(row.due)}</span><span className="cell-sub"><Status tone={statusTone(dueLabel(row.due))}>{dueLabel(row.due)}</Status></span></DataSheetCell>
      <DataSheetCell><button type="button" className="row-action" onClick={() => onOpen({ type: "obligation", id: row.id })}>{row.kind === "customer" ? row.id === "COL-00029" ? receiptDecision === "rejected" ? "Open receipt" : "Review receipt" : "Record receipt" : row.kind === "reimbursement" ? "Record reimbursement" : "Review payment"}<IconChevronRight size={14} /></button></DataSheetCell>
    </DataSheetRow>)}
  </DataSheet>{rows.length === 0 ? <Empty message="No records match these filters." /> : null}<Pagination rangeLabel={"Showing 1–" + rows.length + " of " + rows.length + " items"} page={1} pageCount={1} onPageChange={() => {}} /></div>;
}

function ActivitySheet({ rows, onOpen, compact = false }: { rows: ActivityEvent[]; onOpen: (detail: Detail) => void; compact?: boolean }) {
  return <div className="finance-table"><DataSheet className="finance-activity-sheet" aria-label="Finance activity">
    <DataSheetHeader><DataSheetCell>Date</DataSheetCell><DataSheetCell>Event</DataSheetCell><DataSheetCell>Record</DataSheetCell><DataSheetCell>Member</DataSheetCell></DataSheetHeader>
    {rows.map((row) => <DataSheetRow key={row.id}>
      <DataSheetCell><ActivityDate row={row} /></DataSheetCell>
      <DataSheetCell><button type="button" className="finance-primary-link" onClick={() => onOpen({ type: "activity", id: row.id })}>{row.event}</button><small className="cell-sub">{row.category} · {row.party}</small></DataSheetCell>
      <DataSheetCell><button type="button" className="record-link" onClick={() => onOpen({ type: row.recordId.startsWith("EXP-") ? "expense" : "transaction", id: row.recordId })}>{row.recordId}</button><small className="cell-sub">{row.context}</small></DataSheetCell>
      <DataSheetCell><ActivityMember name={row.actor} /></DataSheetCell>
    </DataSheetRow>)}
    {rows.length === 0 ? <DataSheetRow className="finance-activity-sheet__empty"><DataSheetCell>No activity matches this search.</DataSheetCell></DataSheetRow> : null}
  </DataSheet>{compact || rows.length === 0 ? null : <Pagination rangeLabel={"Showing 1–" + rows.length + " of " + rows.length + " events"} page={1} pageCount={1} onPageChange={() => {}} />}</div>;
}

function Overview({ obligations, activity, receiptDecision, open, navigate }: { obligations: Obligation[]; activity: ActivityEvent[]; receiptDecision: "pending" | "verified" | "rejected"; open: (detail: Detail) => void; navigate: (page: PageId, subview?: string) => void }) {
  const [recentQuery, setRecentQuery] = useState("");
  const recentSearch = recentQuery.trim().toLowerCase();
  const recentActivity = recentSearch ? activity.filter((row) => `${row.event} ${row.category} ${row.party} ${row.actor} ${row.recordId} ${row.context}`.toLowerCase().includes(recentSearch)) : activity.slice(0, 4);
  const customer = obligations.filter((item) => item.kind === "customer").reduce((sum, item) => sum + remaining(item), 0);
  const supplier = obligations.filter((item) => item.kind === "supplier").reduce((sum, item) => sum + remaining(item), 0);
  const due = obligations.filter((item) => remaining(item) > 0 && (item.due <= REVIEW_DATE || item.id === "PAY-00044"));
  return <>
    <div className="scope-bar"><span>Agency: Paryatech · all branches</span><span>Balances as of 26 Sep 2026</span><span>INR</span><span className="scope-bar__preview">Sample workspace</span></div>
    <section className="metrics" aria-label="Finance overview">
      <button className="metric metric--warn" onClick={() => navigate("receivables")}><span className="metric__label">Customer outstanding</span><span className="metric__value"><span className="metric__icon"><IconArrowIn size={15} /></span>{formatMoney(customer)}</span><span className="metric__note">{receiptDecision === "verified" ? "Existing ₹12,000 receipt applied" : receiptDecision === "rejected" ? "₹12,000 remains overdue after proof rejection" : "Includes ₹12,000 awaiting receipt verification"}</span></button>
      <button className="metric metric--bad" onClick={() => navigate("payables")}><span className="metric__label">Outgoing obligations</span><span className="metric__value"><span className="metric__icon"><IconArrowOut size={15} /></span>{formatMoney(supplier + outstanding("reimbursement"))}</span><span className="metric__note">₹65,000 suppliers + ₹7,000 reimbursement</span></button>
      <button className="metric metric--good" onClick={() => navigate("bank")}><span className="metric__label">Recorded bank & cash</span><span className="metric__value"><span className="metric__icon"><IconBank size={15} /></span>{formatMoney(recordedCash)}</span><span className="metric__note">HDFC reconciled through 25 Sep</span></button>
      <button className="metric metric--warn" onClick={() => navigate("controls")}><span className="metric__label">Review needed</span><span className="metric__value"><span className="metric__icon"><IconWarning size={15} /></span>{receiptDecision === "pending" ? "3 items" : "2 items"}</span><span className="metric__note">{receiptDecision === "pending" ? "Receipt proof · bank difference · missing bill" : "Bank difference · missing bill"}</span></button>
    </section>
    <section className="work-section"><div className="section-heading"><div><h2>Needs attention</h2><p>Open amounts and reviews from the same agency records.</p></div><button className="text-link" onClick={() => navigate("receivables")}>See all work<IconChevronRight size={14} /></button></div><ObligationSheet rows={due} onOpen={open} mode="attention" receiptDecision={receiptDecision} /></section>
    <section className="work-section"><div className="section-heading"><div><h2>Cash outlook</h2><p>Expected movements, 27 Sep–10 Oct · INR · all branches.</p></div><span className="as-of-note">Forecast uses dated assumptions</span></div>
      <Summary items={[{ label: "Opening recorded cash", value: formatMoney(recordedCash) }, { label: "Lowest projected daily balance", value: formatMoney(forecastMinimum) }, { label: "Forecast closing cash", value: formatMoney(forecastClosing), note: "If assumed receipts arrive" }]} />
      <div className="forecast-list">{FORECAST.map((row) => <button type="button" key={row.reference} onClick={() => open({ type: row.reference.startsWith("COM") || row.reference.startsWith("CLM") || row.reference.startsWith("INV") ? "obligation" : "statement", id: row.reference })}><span>{row.date}</span><span><strong>{row.source}</strong><small>{row.reference} · {row.basis}</small></span><NumberCell value={Math.abs(row.amount)} direction={row.amount > 0 ? "in" : "out"} /></button>)}</div>
    </section>
    <section className="work-section"><div className="section-heading"><div><h2>Recent activity</h2><p>See when an event happened and when it entered the record.</p></div><button className="text-link" onClick={() => navigate("transactions", "Activity")}>View all activity<IconChevronRight size={14} /></button></div><div className="list-toolbar list-toolbar--activity"><SearchField fullWidth value={recentQuery} onChange={(event) => setRecentQuery(event.target.value)} placeholder="Search recent activity" aria-label="Search recent activity" /></div><ActivitySheet rows={recentActivity} onOpen={open} compact /></section>
  </>;
}

function Receivables({ obligations, receiptDecision, open, onRecord }: { obligations: Obligation[]; receiptDecision: "pending" | "verified" | "rejected"; open: (detail: Detail) => void; onRecord: (type: RecordType, id?: string) => void }) {
  const [view, setView] = useState("To collect"); const [query, setQuery] = useState("");
  const rows = obligations.filter((item) => item.kind === "customer" && remaining(item) > 0 && (item.party + item.booking + item.document).toLowerCase().includes(query.toLowerCase()));
  const total = rows.reduce((sum, item) => sum + remaining(item), 0);
  return <section className="destination-page"><div className="destination-head"><div><h2>Receivables</h2><p>Track customer dues, receipts, advances and refunds.</p></div><Button variant="primary" size="sm" onClick={() => onRecord("Receipt")}><IconPlus size={15} />Record receipt</Button></div>
    <Summary items={[{ label: "Total outstanding", value: formatMoney(total), note: receiptDecision === "pending" ? "Includes pending proof" : "Effective settlements only" }, { label: "Overdue", value: formatMoney(rows.filter((item) => item.due < REVIEW_DATE).reduce((sum, item) => sum + remaining(item), 0)), note: "Subset of outstanding" }, { label: "Receipt awaiting verification", value: receiptDecision === "pending" ? "₹12,000" : "₹0", note: receiptDecision === "pending" ? "Existing receipt; not applied" : receiptDecision === "rejected" ? "Proof rejected; debt still open" : "Existing receipt applied" }, { label: "Unallocated customer money", value: formatMoney(CUSTOMER_ADVANCE.amount), note: "Singh Family advance", onClick: () => setView("Credits & refunds") }]} />
    <ViewTabs items={["To collect", "Invoices", "Customer accounts", "Credits & refunds"]} value={view} onChange={setView} />
    {view === "To collect" ? <><div className="list-toolbar"><SearchField fullWidth value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search customer, booking or invoice" aria-label="Search receivables" /><button className="filter-button" onClick={() => setQuery("")}>Clear filters</button><Button variant="brand" size="sm" onClick={() => downloadCsv("receivables.csv", [["Customer", "Booking", "Document", "Due", "Remaining paise"], ...rows.map((row) => [row.party, row.booking, row.document, row.due, remaining(row)])])}><IconDownload size={14} />Export CSV</Button></div><ObligationSheet rows={rows} onOpen={open} mode="customer" receiptDecision={receiptDecision} /></> : null}
    {view === "Invoices" ? <div className="finance-list">{rows.map((row) => <button key={row.document} onClick={() => open({ type: "obligation", id: row.id })}><span><strong>{row.document}</strong><small>{row.party} · {row.booking} · {row.documentState}</small></span><NumberCell value={remaining(row)} /><IconChevronRight size={15} /></button>)}</div> : null}
    {view === "Customer accounts" ? <div className="finance-list">{rows.map((row) => <button key={row.party} onClick={() => open({ type: "obligation", id: row.id })}><span><strong>{row.party}</strong><small>{row.booking} · 1 open instalment</small></span><NumberCell value={remaining(row)} /><IconChevronRight size={15} /></button>)}</div> : null}
    {view === "Credits & refunds" ? <div className="finance-list"><button onClick={() => open({ type: "advance", id: CUSTOMER_ADVANCE.id })}><span><strong>{CUSTOMER_ADVANCE.party} · unallocated advance</strong><small>{CUSTOMER_ADVANCE.id} · received {formatDate(CUSTOMER_ADVANCE.recorded)} · {CUSTOMER_ADVANCE.receipt}</small></span><NumberCell value={CUSTOMER_ADVANCE.amount} /><IconChevronRight size={15} /></button><button onClick={() => open({ type: "advance", id: REFUND.id })}><span><strong>{REFUND.party} · refund due</strong><small>{REFUND.id} · {REFUND.booking} · supplier recovery tracked separately</small></span><NumberCell value={REFUND.amount} /><IconChevronRight size={15} /></button></div> : null}
  </section>;
}

function Payables({ obligations, open, onRecord }: { obligations: Obligation[]; open: (detail: Detail) => void; onRecord: (type: RecordType, id?: string) => void }) {
  const [view, setView] = useState("To pay"); const [query, setQuery] = useState("");
  const rows = obligations.filter((item) => item.kind !== "customer" && (item.party + item.booking + item.document).toLowerCase().includes(query.toLowerCase()));
  const supplier = rows.filter((item) => item.kind === "supplier").reduce((sum, item) => sum + remaining(item), 0);
  const reimbursement = rows.filter((item) => item.kind === "reimbursement").reduce((sum, item) => sum + remaining(item), 0);
  return <section className="destination-page"><div className="destination-head"><div><h2>Payables</h2><p>See supplier dues and other approved outgoing obligations.</p></div><Button variant="primary" size="sm" onClick={() => onRecord("Supplier payment")}><IconPlus size={15} />Record payment</Button></div>
    <Summary items={[{ label: "All outgoing outstanding", value: formatMoney(supplier + reimbursement) }, { label: "Supplier outstanding", value: formatMoney(supplier), note: "Confirmed commitments" }, { label: "Staff reimbursement due", value: formatMoney(reimbursement), note: "Approved claim; not paid" }]} />
    <ViewTabs items={["To pay", "Supplier bills", "Vendor accounts", "Credits & recoveries"]} value={view} onChange={setView} />
    {view === "To pay" ? <><div className="list-toolbar"><SearchField fullWidth value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search payee, booking or reference" aria-label="Search payables" /><button className="filter-button" onClick={() => setQuery("")}>Clear filters</button><Button variant="brand" size="sm" onClick={() => downloadCsv("payables.csv", [["Payee", "Booking", "Document", "Due", "Remaining paise"], ...rows.map((row) => [row.party, row.booking, row.document, row.due, remaining(row)])])}><IconDownload size={14} />Export CSV</Button></div><ObligationSheet rows={rows} onOpen={open} mode="payable" /></> : null}
    {view === "Supplier bills" ? <div className="finance-list">{rows.filter((row) => row.kind === "supplier").map((row) => <button key={row.id} onClick={() => open({ type: "obligation", id: row.id })}><span><strong>{row.document}</strong><small>{row.party} · {row.item} · {row.documentState}</small></span><NumberCell value={remaining(row)} /><IconChevronRight size={15} /></button>)}</div> : null}
    {view === "Vendor accounts" ? <div className="finance-list">{rows.filter((row) => row.kind === "supplier").map((row) => <button key={row.id} onClick={() => open({ type: "obligation", id: row.id })}><span><strong>{row.party}</strong><small>{row.booking} · 1 confirmed obligation</small></span><NumberCell value={remaining(row)} /><IconChevronRight size={15} /></button>)}</div> : null}
    {view === "Credits & recoveries" ? <div className="finance-note"><h3>No supplier credit has been applied</h3><p>The Nair Family supplier recovery remains a separate case from the customer refund. It will appear here when a recoverable amount is approved.</p><button className="text-link" onClick={() => open({ type: "advance", id: REFUND.id })}>Open linked refund case<IconChevronRight size={14} /></button></div> : null}
  </section>;
}

function Transactions({ rows, activity, open, onRecord, initialView }: { rows: MoneyRecord[]; activity: ActivityEvent[]; open: (detail: Detail) => void; onRecord: (type: RecordType) => void; initialView: string }) {
  const [view, setView] = useState(initialView); const [query, setQuery] = useState(""); const [category, setCategory] = useState("All events");
  const transactions = rows.filter((row) => (row.id + row.party + row.linked + row.type).toLowerCase().includes(query.toLowerCase()));
  const events = activity.filter((row) => (category === "All events" || row.category === category) && (row.event + row.recordId + row.party + row.actor + row.context).toLowerCase().includes(query.toLowerCase()));
  return <section className="destination-page"><div className="destination-head"><div><h2>Transactions</h2><p>One money record per external movement, with its linked business records.</p></div><Button variant="primary" size="sm" onClick={() => onRecord("Receipt")}><IconPlus size={15} />Record money</Button></div>
    <ViewTabs items={["Register", "Activity"]} value={view} onChange={setView} />
    <div className={"list-toolbar" + (view === "Activity" ? " list-toolbar--activity" : "")}><SearchField fullWidth value={query} onChange={(event) => setQuery(event.target.value)} placeholder={view === "Activity" ? "Search event, record or person" : "Search transaction, party or booking"} aria-label="Search transactions and activity" />{view === "Activity" ? <select className="filter-button" aria-label="Filter activity category" value={category} onChange={(event) => setCategory(event.target.value)}>{["All events", "Money", "Verification", "Allocation", "Review", "Bank match"].map((item) => <option key={item}>{item}</option>)}</select> : null}<Button variant="brand" size="sm" onClick={() => view === "Activity" ? downloadCsv("finance-activity.csv", [["Event ID", "Event", "Occurred", "Recorded", "Actor", "Record"], ...events.map((row) => [row.id, row.event, row.occurredAt, row.recordedAt, row.actor, row.recordId])]) : downloadCsv("transactions.csv", [["Reference", "Type", "Party", "Occurred", "Recorded", "Linked", "Amount paise", "Verification"], ...transactions.map((row) => [row.id, row.type, row.party, row.occurredAt, row.recordedAt, row.linked, row.amount, row.verification])])}><IconDownload size={14} />Export CSV</Button></div>
    {view === "Activity" ? <ActivitySheet rows={events} onOpen={open} /> : <div className="finance-table"><DataSheet className="finance-transaction-sheet" aria-label="Transactions"><DataSheetHeader><DataSheetCell>Reference / date</DataSheetCell><DataSheetCell>Type & party</DataSheetCell><DataSheetCell>Linked record(s)</DataSheetCell><DataSheetCell>Amount</DataSheetCell><DataSheetCell>Verification</DataSheetCell><DataSheetCell>Account</DataSheetCell></DataSheetHeader>{transactions.map((row) => <DataSheetRow key={row.id}><DataSheetCell><button className="record-link" onClick={() => open({ type: "transaction", id: row.id })}>{row.id}</button><small className="cell-sub">{formatDate(row.occurredAt)}</small></DataSheetCell><DataSheetCell><span className="cell-main">{row.type}</span><small className="cell-sub">{row.party}</small></DataSheetCell><DataSheetCell><button className="cell-link cell-main" onClick={() => open({ type: "transaction", id: row.id })}>{row.linked}</button><small className="cell-sub">{row.allocation} · {row.bankMatch}</small></DataSheetCell><DataSheetCell><NumberCell value={row.amount} direction={row.direction} /></DataSheetCell><DataSheetCell><Status tone={statusTone(row.verification)}>{row.verification}</Status></DataSheetCell><DataSheetCell>{row.account}</DataSheetCell></DataSheetRow>)}</DataSheet>{transactions.length === 0 ? <Empty message="No transactions match this search." /> : null}<Pagination rangeLabel={"Showing 1–" + transactions.length + " of " + transactions.length + " transactions"} page={1} pageCount={1} onPageChange={() => {}} /></div>}
  </section>;
}

function Expenses({ rows, open, onRecord }: { rows: Expense[]; open: (detail: Detail) => void; onRecord: (type: RecordType) => void }) {
  const [query, setQuery] = useState(""); const [scope, setScope] = useState("All scopes");
  const filtered = rows.filter((row) => (scope === "All scopes" || (scope === "Agency" ? row.scope.startsWith("Agency") : !row.scope.startsWith("Agency"))) && (row.category + row.payee + row.id).toLowerCase().includes(query.toLowerCase()));
  const agency = rows.filter((row) => row.scope.startsWith("Agency")).reduce((sum, row) => sum + row.amount, 0);
  const booking = rows.filter((row) => !row.scope.startsWith("Agency")).reduce((sum, row) => sum + row.amount, 0);
  return <section className="destination-page"><div className="destination-head"><div><h2>Expenses</h2><p>Agency expenses, trip costs and reimbursements.</p></div><Button variant="primary" size="sm" onClick={() => onRecord("Agency payment")}><IconPlus size={15} />Record reimbursement</Button></div>
    <Summary items={[{ label: "Listed expenses · September", value: formatMoney(agency + booking), note: "Cost counted once" }, { label: "Agency expenses", value: formatMoney(agency) }, { label: "Booking expenses", value: formatMoney(booking) }, { label: "Reimbursement due", value: formatMoney(rows.filter((row) => row.payment === "Reimbursement due").reduce((sum, row) => sum + row.amount, 0)), note: "Unpaid subset, not another expense" }]} />
    <div className="list-toolbar"><SearchField fullWidth value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search expense or payee" aria-label="Search expenses" /><select className="filter-button" value={scope} onChange={(event) => setScope(event.target.value)} aria-label="Filter expense scope"><option>All scopes</option><option>Agency</option><option>Booking</option></select><Button variant="brand" size="sm" onClick={() => downloadCsv("expenses.csv", [["ID", "Category", "Payee", "Scope", "Incurred", "Due", "Amount paise", "Review", "Payment"], ...filtered.map((row) => [row.id, row.category, row.payee, row.scope, row.incurred, row.due, row.amount, row.review, row.payment])])}><IconDownload size={14} />Export CSV</Button></div>
    <div className="finance-table"><DataSheet className="finance-expense-sheet" aria-label="Expenses"><DataSheetHeader><DataSheetCell>Expense</DataSheetCell><DataSheetCell>Payee / scope</DataSheetCell><DataSheetCell>Incurred / due</DataSheetCell><DataSheetCell>Amount</DataSheetCell><DataSheetCell>Review</DataSheetCell><DataSheetCell>Payment</DataSheetCell></DataSheetHeader>{filtered.map((row) => <DataSheetRow key={row.id}><DataSheetCell><button className="finance-primary-link" onClick={() => open({ type: "expense", id: row.id })}>{row.category}</button><small className="cell-sub">{row.id} · {row.evidence}</small></DataSheetCell><DataSheetCell>{row.payee}<small className="cell-sub">{row.scope}</small></DataSheetCell><DataSheetCell>{formatDate(row.incurred)}<small className="cell-sub">Due {formatDate(row.due)}</small></DataSheetCell><DataSheetCell><NumberCell value={row.amount} /></DataSheetCell><DataSheetCell><Status tone="done">{row.review}</Status></DataSheetCell><DataSheetCell><Status tone={statusTone(row.payment)}>{row.payment}</Status></DataSheetCell></DataSheetRow>)}</DataSheet><Pagination rangeLabel={"Showing 1–" + filtered.length + " of " + filtered.length + " expenses"} page={1} pageCount={1} onPageChange={() => {}} /></div>
  </section>;
}

function Bank({ open }: { open: (detail: Detail) => void }) {
  const [account, setAccount] = useState<"hdfc" | "cash">("hdfc");
  return <section className="destination-page"><div className="destination-head"><div><h2>Bank & cash</h2><p>Compare recorded accounts with bank statements or cash counts.</p></div></div>
    <div className="bank-account-grid">{ACCOUNTS.map((item) => <button type="button" key={item.id} className={"bank-account finance-account-button" + (account === item.id ? " bank-account--primary" : "")} onClick={() => setAccount(item.id)}><div><span className="bank-account__icon"><IconBank /></span><span><strong>{item.name}</strong><small>{item.meta}</small></span></div><b>{formatMoney(item.recorded)}</b><footer><Status tone={item.id === "hdfc" ? "done" : "open"}>{item.lastReview}</Status><span>Open account <IconChevronRight size={14} /></span></footer></button>)}</div>
    {account === "hdfc" ? <><div className="finance-account-context">HDFC Bank · ending 2163 <span>Statement: 26 Sep 2026</span><span>Last reconciled: 25 Sep 2026</span></div><div className="reconcile-banner"><span className="reconcile-banner__icon"><IconWarning /></span><div><strong>26 Sep comparison remains open</strong><p>A ₹7,500 statement credit is unmatched. The visible entries still leave an unexplained ₹6,750 net difference.</p></div><Button variant="brand" size="sm" onClick={() => open({ type: "statement", id: "BANK-ROW-8821" })}>Review statement row</Button></div><Summary items={[{ label: "Recorded book balance", value: formatMoney(ACCOUNTS[0].recorded) }, { label: "Statement closing balance", value: formatMoney(statementClosing), note: "26 Sep · HDFC 2163" }, { label: "Raw difference", value: formatMoney(statementDifference), note: "Statement minus book" }, { label: "Unexplained after visible row", value: formatMoney(unexplainedAfterVisibleRow), note: "Not reconciled" }]} /><div className="finance-list"><button onClick={() => open({ type: "statement", id: "BANK-ROW-8821" })}><span><strong>Unmatched incoming statement row</strong><small>BANK-ROW-8821 · 26 Sep · payer unidentified · no accepted match</small></span><NumberCell value={unmatchedStatementRow} direction="in" /><IconChevronRight size={15} /></button></div></> : <><div className="finance-account-context">Petty cash · Kochi office <span>Custodian: Meera Iyer</span></div><div className="finance-note"><h3>Cash count due today</h3><p>Recorded balance: {formatMoney(ACCOUNTS[1].recorded)}. Enter a counted amount and count date through the authorised cash count workflow. Bank statement imports do not reconcile petty cash.</p></div></>}
  </section>;
}

const REPORTS = [
  { id: "customer", title: "Customer ageing", basis: "Outstanding as of 26 Sep 2026", description: "Open customer instalments by due date." },
  { id: "supplier", title: "Supplier ageing", basis: "Outstanding as of 26 Sep 2026", description: "Confirmed dues and missing supplier bills." },
  { id: "statement", title: "Customer & vendor statements", basis: "Through 26 Sep 2026", description: "Party obligations and effective applications." },
  { id: "money", title: "Receipts & payments", basis: "Occurred 1–26 Sep 2026", description: "External money movements by actual payment date." },
  { id: "expenses", title: "Expenses & reimbursements", basis: "Incurred 1–26 Sep 2026", description: "Agency and trip costs, with unpaid claims." },
  { id: "profit", title: "Booking profitability", basis: "Confirmed booking cohort · projected", description: "Accepted price less confirmed direct cost." },
  { id: "cash", title: "Cash outlook", basis: "27 Sep–10 Oct 2026", description: "Dated expected account movements." },
  { id: "advances", title: "Advances & recoveries", basis: "Open as of 26 Sep 2026", description: "Unallocated advances and open refund work." },
  { id: "exceptions", title: "Exceptions & closing", basis: "Review as of 26 Sep 2026", description: "Verification, missing documents and unexplained cash." },
];
function StatementReport({ obligations, transactions, open }: { obligations: Obligation[]; transactions: MoneyRecord[]; open: (detail: Detail) => void }) {
  const [scope, setScope] = useState<"customer" | "supplier">("customer");
  const [party, setParty] = useState("XYZ Family");
  const parties = [...new Set(obligations.filter((item) => item.kind === scope).map((item) => item.party))];
  const entries = [
    ...obligations.filter((item) => item.kind === scope && item.party === party).map((item) => ({ date: item.postedAt, id: item.document, description: item.item + " · " + item.booking, charge: item.amount, applied: 0, detail: { type: "obligation", id: item.id } as Detail })),
    ...transactions.filter((item) => item.party === party && item.verification === "Verified" && item.allocation.endsWith(" applied") && (scope === "customer" ? item.type === "Receipt" : item.type === "Supplier payment")).map((item) => ({ date: item.occurredAt, id: item.id, description: item.type + " · " + item.linked, charge: 0, applied: item.amount, detail: { type: "transaction", id: item.id } as Detail })),
  ].sort((a, b) => a.date.localeCompare(b.date));
  let balance = 0;
  const lines = entries.map((item) => { balance += item.charge - item.applied; return { ...item, balance }; });
  const charges = entries.reduce((sum, item) => sum + item.charge, 0);
  const applied = entries.reduce((sum, item) => sum + item.applied, 0);
  return <><div className="statement-toolbar"><label>Account type<select value={scope} onChange={(event) => { const next = event.target.value as "customer" | "supplier"; setScope(next); setParty(obligations.find((item) => item.kind === next)?.party || ""); }}><option value="customer">Customer</option><option value="supplier">Supplier</option></select></label><label>Party<select value={party} onChange={(event) => setParty(event.target.value)}>{parties.map((item) => <option key={item}>{item}</option>)}</select></label><span>1–26 Sep 2026 · INR · effective applications only</span><Button variant="brand" size="sm" onClick={() => downloadCsv("statement-" + party.toLowerCase().replaceAll(" ", "-") + ".csv", [["Date", "Reference", "Description", "Charge paise", "Applied paise", "Balance paise"], ...lines.map((item) => [item.date, item.id, item.description, item.charge, item.applied, item.balance])])}><IconDownload size={14} />Export CSV</Button></div>
    <Summary items={[{ label: "Opening balance", value: formatMoney(0), note: "Sample period begins 1 Sep" }, { label: "Charges / commitments", value: formatMoney(charges) }, { label: "Effective applications", value: formatMoney(applied) }, { label: "Closing balance", value: formatMoney(balance), note: "Unverified proof excluded" }]} />
    <div className="finance-table"><DataSheet className="finance-statement-sheet" aria-label={party + " statement"}><DataSheetHeader><DataSheetCell>Date</DataSheetCell><DataSheetCell>Reference / item</DataSheetCell><DataSheetCell>Charge</DataSheetCell><DataSheetCell>Applied</DataSheetCell><DataSheetCell>Balance</DataSheetCell></DataSheetHeader>{lines.map((item) => <DataSheetRow key={item.id}><DataSheetCell>{formatDate(item.date)}</DataSheetCell><DataSheetCell><button className="record-link" onClick={() => open(item.detail)}>{item.id}</button><small className="cell-sub">{item.description}</small></DataSheetCell><DataSheetCell><NumberCell value={item.charge} /></DataSheetCell><DataSheetCell><NumberCell value={item.applied} /></DataSheetCell><DataSheetCell><NumberCell value={item.balance} /></DataSheetCell></DataSheetRow>)}</DataSheet></div>
    {party === "Kapoor Group" && transactions.some((item) => item.id === "RCPT-2026-0088" && item.verification !== "Verified") ? <p className="statement-pending">₹12,000 receipt proof exists but is not an effective application. Open RCPT-2026-0088 in Transactions to review it.</p> : null}</>;
}
function Reports({ obligations, transactions, expenses, receiptDecision, open }: { obligations: Obligation[]; transactions: MoneyRecord[]; expenses: Expense[]; receiptDecision: "pending" | "verified" | "rejected"; open: (detail: Detail) => void }) {
  const [selected, setSelected] = useState<string | null>(null);
  const report = REPORTS.find((item) => item.id === selected);
  const rows: Array<{ id: string; label: string; context: string; amount: number; detail: Detail }> = selected === "customer" || selected === "supplier" || selected === "statement" ? obligations.filter((item) => selected === "statement" || item.kind === selected).map((item) => ({ id: item.document, label: item.party, context: item.booking + " · " + dueLabel(item.due), amount: remaining(item), detail: { type: "obligation", id: item.id } })) : selected === "money" ? transactions.filter((item) => item.type !== "Transfer" && item.verification === "Verified").map((item) => ({ id: item.id, label: item.party, context: item.type + " · " + formatDate(item.occurredAt), amount: item.direction === "in" ? item.amount : -item.amount, detail: { type: "transaction", id: item.id } })) : selected === "expenses" ? expenses.map((item) => ({ id: item.id, label: item.category, context: item.payee + " · " + item.payment, amount: item.amount, detail: { type: "expense", id: item.id } })) : selected === "cash" ? FORECAST.map((item) => ({ id: item.reference, label: item.source, context: item.date + " · " + item.basis, amount: item.amount, detail: { type: "statement", id: item.reference } })) : selected === "advances" ? [{ id: CUSTOMER_ADVANCE.id, label: CUSTOMER_ADVANCE.party, context: "Unallocated customer advance", amount: CUSTOMER_ADVANCE.amount, detail: { type: "advance", id: CUSTOMER_ADVANCE.id } }, { id: REFUND.id, label: REFUND.party, context: "Approved refund due", amount: REFUND.amount, detail: { type: "advance", id: REFUND.id } }] : selected === "exceptions" ? [{ id: "RCPT-2026-0088", label: "Kapoor Group", context: "Receipt verification pending", amount: 1_200_000, detail: { type: "transaction", id: "RCPT-2026-0088" } }, { id: "BANK-ROW-8821", label: "HDFC Bank", context: "Unmatched row; difference unexplained", amount: unmatchedStatementRow, detail: { type: "statement", id: "BANK-ROW-8821" } }] : [];
  if (selected === "profit") rows.push({ id: "BK-2026-000003", label: "XYZ Family · Dubai", context: formatMoney(OBLIGATIONS.filter((item) => item.kind === "customer" && item.booking === "BK-2026-000003").reduce((sum, item) => sum + item.amount, 0)) + " accepted price − " + formatMoney(OBLIGATIONS.filter((item) => item.kind === "supplier" && item.booking === "BK-2026-000003").reduce((sum, item) => sum + item.amount, 0)) + " confirmed direct cost · projected", amount: bookingProjectedMargin, detail: { type: "obligation", id: "COL-00031" } });
  if (selected === "exceptions" && receiptDecision !== "pending") rows.splice(0, 1);
  const totalLabel = selected === "money" ? "Net recorded movement" : selected === "cash" ? "Net forecast movement" : selected === "profit" ? "Projected direct margin" : "Displayed total";
  const showTotal = selected !== "statement" && selected !== "advances" && selected !== "exceptions";
  if (report?.id === "statement") return <section className="destination-page"><div className="destination-head"><div><h2>Reports</h2><p>Customer and supplier account statements.</p></div></div><div className="report-detail-head"><button className="text-link" onClick={() => setSelected(null)}>← All reports</button><div><h3>{report.title}</h3><p>{report.basis} · INR · Paryatech, all branches</p></div></div><StatementReport obligations={obligations} transactions={transactions} open={open} /></section>;
  return <section className="destination-page"><div className="destination-head"><div><h2>Reports</h2><p>Open a report to review its basis, totals and source records.</p></div></div>{!report ? <div className="report-grid">{REPORTS.map((item) => <button key={item.id} className="report-card" onClick={() => setSelected(item.id)}><span className="report-card__icon"><IconReceipt size={18} /></span><span><strong>{item.title}</strong><small>{item.description}</small><em>{item.basis} · INR</em></span><IconChevronRight size={16} /></button>)}</div> : <><div className="report-detail-head"><button className="text-link" onClick={() => setSelected(null)}>← All reports</button><div><h3>{report.title}</h3><p>{report.basis} · INR · Paryatech, all branches</p></div><Button variant="brand" size="sm" onClick={() => downloadCsv(report.id + "-report.csv", [["Reference", "Name", "Context", "Amount paise"], ...rows.map((row) => [row.id, row.label, row.context, row.amount])])}><IconDownload size={14} />Export CSV</Button></div><Summary items={[{ label: "Rows", value: String(rows.length) }, ...(showTotal ? [{ label: totalLabel, value: formatMoney(rows.reduce((sum, row) => sum + row.amount, 0)), note: selected === "money" ? "Verified movements; not profit" : "For selected report basis" }] : [])]} /><div className="finance-list">{rows.map((row) => <button key={row.id} onClick={() => open(row.detail)}><span><strong>{row.label}</strong><small>{row.id} · {row.context}</small></span><NumberCell value={row.amount} /><IconChevronRight size={15} /></button>)}</div></>}</section>;
}

function Controls({ open, navigate, receiptDecision }: { open: (detail: Detail) => void; navigate: (page: PageId, subview?: string) => void; receiptDecision: "pending" | "verified" | "rejected" }) {
  const [view, setView] = useState("September review");
  return <section className="destination-page"><div className="destination-head"><div><h2>Approvals & closing</h2><p>Review exceptions and keep the September period open until checks are complete.</p></div></div><ViewTabs items={["Payment approvals", "September review", "Adjustments", "Accounting export"]} value={view} onChange={setView} />
    {view === "Payment approvals" ? <div className="finance-note"><h3>No payment approval request is pending</h3><p>Approval is separate from a completed payment. Authorised staff can record money that already moved, subject to verification and review.</p></div> : null}
    {view === "September review" ? <><div className="finance-note"><h3>September review · period remains open</h3><p>Open debts and reimbursements can carry forward when recorded correctly. The current checks concern evidence and account differences.</p></div><div className="finance-list"><button onClick={() => navigate("bank")}><span><strong>HDFC comparison needs explanation</strong><small>26 Sep · raw difference ₹750; unmatched credit ₹7,500</small></span><Status tone="blocked">Unresolved</Status><IconChevronRight size={15} /></button><button onClick={() => open({ type: "obligation", id: "PAY-00044" })}><span><strong>Trailmakers hotel bill not received</strong><small>Confirmed commitment remains due; no duplicate cost</small></span><Status tone="open">Follow up</Status><IconChevronRight size={15} /></button>{receiptDecision === "pending" ? <button onClick={() => navigate("transactions", "Activity")}><span><strong>Kapoor receipt awaiting verification</strong><small>Receipt exists; customer debt is still overdue</small></span><Status tone="open">Review</Status><IconChevronRight size={15} /></button> : null}</div></> : null}
    {view === "Adjustments" ? <div className="finance-note"><h3>No adjustment request is pending</h3><p>Posted amounts require a reviewed reversal or amendment. This preview does not permit direct balance edits.</p></div> : null}
    {view === "Accounting export" ? <div className="finance-note"><h3>Accounting export is not configured</h3><p>Set document ownership, account mapping and review permissions before a batch can be previewed or exported. CSV exports on the lists are operational data only.</p></div> : null}
  </section>;
}

function DetailPanel({ detail, obligations, transactions, expenses, activity, receiptDecision, onClose, onRecord, onReceiptDecision, open }: { detail: Detail | null; obligations: Obligation[]; transactions: MoneyRecord[]; expenses: Expense[]; activity: ActivityEvent[]; receiptDecision: string; onClose: () => void; onRecord: (type: RecordType, id?: string) => void; onReceiptDecision: (decision: "verified" | "rejected") => void; open: (detail: Detail) => void }) {
  if (!detail) return null;
  const obligation = detail.type === "obligation" ? obligations.find((item) => item.id === detail.id || item.document === detail.id) : undefined;
  const transaction = detail.type === "transaction" ? transactions.find((item) => item.id === detail.id) : undefined;
  const expense = detail.type === "expense" ? expenses.find((item) => item.id === detail.id) : undefined;
  const event = detail.type === "activity" ? activity.find((item) => item.id === detail.id) : undefined;
  const isKapoor = obligation?.id === "COL-00029" || transaction?.id === "RCPT-2026-0088";
  const title = obligation?.item || transaction?.type || expense?.category || event?.event || (detail.id === "BANK-ROW-8821" ? "Unmatched statement row" : detail.id === CUSTOMER_ADVANCE.id ? "Unallocated customer advance" : detail.id === REFUND.id ? "Customer refund" : "Source record");
  const amount = obligation ? remaining(obligation) : transaction?.amount ?? expense?.amount ?? (detail.id === CUSTOMER_ADVANCE.id ? CUSTOMER_ADVANCE.amount : detail.id === REFUND.id ? REFUND.amount : detail.id === "BANK-ROW-8821" ? unmatchedStatementRow : undefined);
  const linkedEvents = activity.filter((item) => item.recordId === (transaction?.id || expense?.id || event?.recordId) || item.context.includes(obligation?.booking || "__none__"));
  return <div className="drawer-backdrop" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose(); }}><aside className="detail-drawer finance-detail" role="dialog" aria-modal="true" aria-labelledby="detail-title"><header><div><span>{detail.id}</span><h2 id="detail-title">{title}</h2></div><IconButton label="Close details" onClick={onClose}><IconClose /></IconButton></header><div className="detail-drawer__body">
    {amount !== undefined ? <div className="detail-amount"><span>{obligation ? "Remaining" : "Amount"}</span><strong>{formatMoney(amount)}</strong></div> : null}
    {obligation ? <><dl className="detail-fields"><div><dt>Party</dt><dd>{obligation.party}</dd></div><div><dt>Booking</dt><dd>{obligation.booking}</dd></div><div><dt>Document</dt><dd>{obligation.document}</dd></div><div><dt>Due</dt><dd>{formatDate(obligation.due)}</dd></div><div><dt>Due state</dt><dd>{dueLabel(obligation.due)}</dd></div><div><dt>Document state</dt><dd>{obligation.documentState}</dd></div><div><dt>Owner</dt><dd>{obligation.owner}</dd></div><div><dt>Original amount</dt><dd>{formatMoney(obligation.amount)}</dd></div></dl><section className="why-panel"><span><IconFinance size={16} /></span><div><h3>Why this is here</h3><p>{obligation.note}</p></div></section></> : null}
    {transaction ? <><dl className="detail-fields"><div><dt>Party</dt><dd>{transaction.party}</dd></div><div><dt>Occurred</dt><dd>{formatDateTime(transaction.occurredAt)}</dd></div><div><dt>Recorded</dt><dd>{formatDateTime(transaction.recordedAt)}</dd></div><div><dt>Recorded by</dt><dd>{transaction.recordedBy}</dd></div><div><dt>Linked records</dt><dd>{transaction.linked}</dd></div><div><dt>External reference</dt><dd>{transaction.externalReference}</dd></div><div><dt>Verification</dt><dd>{transaction.verification}</dd></div><div><dt>Allocation</dt><dd>{transaction.allocation}</dd></div><div><dt>Bank match</dt><dd>{transaction.bankMatch}</dd></div><div><dt>Account</dt><dd>{transaction.account}</dd></div></dl><p className="detail-help">Verification, allocation and bank match are separate decisions. The original money record appears once in the register.</p></> : null}
    {expense ? <><dl className="detail-fields"><div><dt>Payee</dt><dd>{expense.payee}</dd></div><div><dt>Scope</dt><dd>{expense.scope}</dd></div><div><dt>Incurred</dt><dd>{formatDate(expense.incurred)}</dd></div><div><dt>Payment due</dt><dd>{formatDate(expense.due)}</dd></div><div><dt>Review</dt><dd>{expense.review}</dd></div><div><dt>Payment</dt><dd>{expense.payment}</dd></div><div><dt>Evidence</dt><dd>{expense.evidence}</dd></div><div><dt>Linked payment</dt><dd>{expense.linkedPayment || "None recorded"}</dd></div></dl>{expense.linkedPayment ? <button className="text-link" onClick={() => open({ type: "transaction", id: expense.linkedPayment || "" })}>Open linked payment<IconChevronRight size={14} /></button> : null}</> : null}
    {event ? <><dl className="detail-fields"><div><dt>Happened</dt><dd>{formatDateTime(event.occurredAt)}</dd></div><div><dt>Recorded</dt><dd>{formatDateTime(event.recordedAt)}</dd></div><div><dt>By</dt><dd>{event.actor}</dd></div><div><dt>Category</dt><dd>{event.category}</dd></div><div><dt>Record</dt><dd>{event.recordId}</dd></div><div><dt>Context</dt><dd>{event.context}</dd></div></dl><section className="why-panel"><span><IconFinance size={16} /></span><div><h3>What changed</h3><p>{event.detail}</p></div></section><button className="text-link" onClick={() => open({ type: event.recordId.startsWith("EXP-") ? "expense" : "transaction", id: event.recordId })}>Open source record<IconChevronRight size={14} /></button></> : null}
    {detail.type === "statement" ? <section className="why-panel"><span><IconWarning size={16} /></span><div><h3>{detail.id === "BANK-ROW-8821" ? "Match still required" : "Forecast source"}</h3><p>{detail.id === "BANK-ROW-8821" ? "A ₹7,500 credit appears on the 26 Sep HDFC statement. No existing transaction has been accepted as its match. The raw book-to-statement difference is ₹750, so this row alone cannot explain the period." : "This dated expected movement appears in the cash outlook. It has not been counted in opening cash."}</p></div></section> : null}
    {detail.type === "advance" ? <section className="why-panel"><span><IconFinance size={16} /></span><div><h3>{detail.id === REFUND.id ? "Separate refund and recovery" : "Party-owned advance"}</h3><p>{detail.id === REFUND.id ? "The approved customer refund is due on 29 Sep. Supplier recovery remains a separate claim; refund approval is not a paid transaction." : "This ₹10,000 belongs to Singh Family. It is not applied to another customer's invoice and is not subtracted from agency receivables."}</p></div></section> : null}
    {linkedEvents.length && !event ? <section className="finance-detail-activity"><h3>Related activity</h3><div className="finance-detail-activity__sheet">{linkedEvents.slice(0, 5).map((item) => <button key={item.id} onClick={() => open({ type: "activity", id: item.id })}><ActivityDate row={item} /><span className="finance-detail-activity__event"><strong>{item.event}</strong><small>{item.actor} · {activityRole(item.actor)}</small></span></button>)}</div></section> : null}
  </div><footer><Button variant="ghost" size="sm" onClick={onClose}>Close</Button>{isKapoor && receiptDecision === "pending" ? <><Button variant="brand" size="sm" onClick={() => onReceiptDecision("rejected")}>Reject proof</Button><Button variant="primary" size="sm" onClick={() => onReceiptDecision("verified")}>Verify and apply existing receipt</Button></> : obligation?.kind === "customer" && !isKapoor ? <Button variant="primary" size="sm" onClick={() => onRecord("Receipt", obligation.id)}>Record receipt</Button> : obligation?.kind === "supplier" ? <Button variant="primary" size="sm" onClick={() => onRecord("Supplier payment", obligation.id)}>Record payment</Button> : obligation?.kind === "reimbursement" || expense?.payment === "Reimbursement due" ? <Button variant="primary" size="sm" onClick={() => onRecord("Agency payment", obligation?.id || "CLM-2026-0012")}>Record reimbursement</Button> : null}</footer></aside></div>;
}

function RecordPanel({ kind, obligationId, obligations, transactions, onClose, onSave }: { kind: RecordType | null; obligationId?: string; obligations: Obligation[]; transactions: MoneyRecord[]; onClose: () => void; onSave: (record: MoneyRecord, event: ActivityEvent) => void }) {
  const [type, setType] = useState<RecordType>(kind || "Receipt"); const [target, setTarget] = useState(obligationId || ""); const [amount, setAmount] = useState(""); const [occurred, setOccurred] = useState("2026-09-26"); const [reference, setReference] = useState(""); const [error, setError] = useState("");
  if (!kind) return null;
  const eligible = obligations.filter((item) => type === "Receipt" ? item.kind === "customer" : type === "Supplier payment" ? item.kind === "supplier" : item.kind === "reimbursement");
  const selected = eligible.find((item) => item.id === target);
  const submit = (event: FormEvent) => {
    event.preventDefault();
    const paise = Math.round(Number(amount) * 100);
    if (!Number.isSafeInteger(paise) || paise <= 0) { setError("Enter a valid amount greater than zero."); return; }
    if (type !== "Account transfer" && !selected) { setError("Choose the existing amount this payment relates to."); return; }
    if (selected && paise > remaining(selected)) { setError("Amount exceeds the remaining eligible balance."); return; }
    if (type === "Account transfer" && paise > ACCOUNTS[0].recorded) { setError("Transfer exceeds the recorded source balance."); return; }
    if (!reference.trim()) { setError("Enter the external payment or transfer reference."); return; }
    if (transactions.some((row) => row.externalReference.trim().toLowerCase() === reference.trim().toLowerCase())) { setError("This external reference is already recorded. Open the existing transaction instead."); return; }
    const now = new Date().toISOString(); const prefix = type === "Receipt" ? "RCPT" : type === "Account transfer" ? "TRF" : "PAY"; const id = prefix + "-PREVIEW-" + Date.now().toString().slice(-6);
    const record: MoneyRecord = { id, type: type === "Account transfer" ? "Transfer" : type, party: type === "Account transfer" ? "HDFC Bank → Petty cash" : selected?.party || "", amount: paise, direction: type === "Receipt" ? "in" : type === "Account transfer" ? "neutral" : "out", occurredAt: occurred + "T12:00:00", recordedAt: now, recordedBy: "Vrushabh Jain", account: type === "Account transfer" ? "HDFC Bank → Petty cash" : "HDFC Bank · 2163", linked: type === "Account transfer" ? "Internal account transfer" : (selected?.booking || "") + " / " + (selected?.document || ""), verification: "Awaiting verification", allocation: type === "Account transfer" ? "Not applicable" : "Not applied", bankMatch: "Unmatched", externalReference: reference.trim() };
    const activityEvent: ActivityEvent = { id: "EVT-PREVIEW-" + Date.now().toString().slice(-6), event: type === "Account transfer" ? "Account transfer recorded" : type + " recorded", category: "Money", occurredAt: record.occurredAt, recordedAt: now, actor: "Vrushabh Jain", recordId: id, party: record.party, context: record.linked, detail: "The external money movement was entered for review. Verification and effective allocation remain separate; outstanding balances did not change." };
    onSave(record, activityEvent);
  };
  return <div className="drawer-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><aside className="record-panel" role="dialog" aria-modal="true" aria-labelledby="record-title"><header><div><span>Money already moved outside Paryatech</span><h2 id="record-title">Record money</h2></div><IconButton label="Close record form" onClick={onClose}><IconClose /></IconButton></header><form onSubmit={submit}>
    <div className="record-kind" role="group" aria-label="Money record type">{(["Receipt", "Supplier payment", "Agency payment", "Account transfer"] as RecordType[]).map((item) => <button type="button" key={item} className={item === type ? "active" : ""} onClick={() => { setType(item); setTarget(""); setError(""); }}>{item}</button>)}</div>
    <div className="record-guidance"><IconWarning size={16} /><p>This records an external payment or transfer. It does not send money. New records await verification and do not settle an obligation yet.</p></div>
    {type !== "Account transfer" ? <label><span>{type === "Receipt" ? "Customer amount to collect" : type === "Supplier payment" ? "Supplier obligation" : "Approved reimbursement"}</span><select value={target} onChange={(event) => setTarget(event.target.value)} required><option value="">Choose an existing record</option>{eligible.map((item) => <option key={item.id} value={item.id}>{item.party} · {item.document} · {formatMoney(remaining(item))} remaining</option>)}</select><small>The payment links to this existing obligation. It does not create another charge.</small></label> : <div className="finance-transfer-route">From HDFC Bank · 2163 → Petty cash · Kochi</div>}
    <div className="form-row"><label><span>Amount (INR)</span><input type="number" min="0.01" step="0.01" inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} required placeholder="0.00" /></label><label><span>When money moved</span><input type="date" max="2026-09-26" value={occurred} onChange={(event) => setOccurred(event.target.value)} required /></label></div>
    <label><span>External reference</span><input value={reference} onChange={(event) => setReference(event.target.value)} placeholder="Bank UTR, UPI or cash voucher" required /></label><p className="recorded-time-note">Recorded time is captured separately when you save.</p>{error ? <p className="form-error" role="alert">{error}</p> : null}
    <footer><Button variant="ghost" size="sm" type="button" onClick={onClose}>Cancel</Button><Button variant="primary" size="sm" type="submit">Record for verification</Button></footer>
  </form></aside></div>;
}

export default function FinanceApp() {
  const [page, setPage] = useState<PageId>("overview"); const [transactionView, setTransactionView] = useState("Register"); const [detail, setDetail] = useState<Detail | null>(null); const [record, setRecord] = useState<{ kind: RecordType; id?: string } | null>(null); const [receiptDecision, setReceiptDecision] = useState<"pending" | "verified" | "rejected">("pending"); const [newTransactions, setNewTransactions] = useState<MoneyRecord[]>([]); const [newActivity, setNewActivity] = useState<ActivityEvent[]>([]); const [toast, setToast] = useState("");
  const [notesOpen, setNotesOpen] = useState(false); const [notes, setNotes] = useState<string[]>([]); const [noteDraft, setNoteDraft] = useState("");
  const returnFocus = useRef<HTMLElement | null>(null);
  useEffect(() => {
    if (!detail && !record && !notesOpen) { returnFocus.current?.focus(); returnFocus.current = null; return; }
    if (!returnFocus.current && document.activeElement instanceof HTMLElement) returnFocus.current = document.activeElement;
    const frame = document.querySelector<HTMLElement>(".detail-drawer, .record-panel, .finance-notes-panel");
    frame?.querySelector<HTMLElement>("header button")?.focus();
    const onKey = (event: KeyboardEvent) => {
      if (event.key === "Escape") { setDetail(null); setRecord(null); setNotesOpen(false); }
      if (event.key !== "Tab" || !frame) return;
      const focusables = [...frame.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), select:not([disabled]), a[href]')];
      const first = focusables[0]; const last = focusables[focusables.length - 1];
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); }
      else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); }
    };
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [detail, record, notesOpen]);
  const obligations = useMemo(() => OBLIGATIONS.map((item) => item.id === "COL-00029" && receiptDecision === "verified" ? { ...item, applied: 1_200_000, note: "The existing ₹12,000 receipt was verified and applied. This instalment is settled." } : item), [receiptDecision]);
  const transactions = useMemo(() => [...newTransactions, ...TRANSACTIONS.map((item) => item.id === "RCPT-2026-0088" ? { ...item, verification: receiptDecision === "verified" ? "Verified" : receiptDecision === "rejected" ? "Proof rejected" : item.verification, allocation: receiptDecision === "verified" ? "₹12,000 applied" : "Not applied" } : item)], [newTransactions, receiptDecision]);
  const activity = useMemo(() => [...newActivity, ...ACTIVITY], [newActivity]);
  const navGroups = useMemo(() => buildNavGroups((label) => setToast(label + " opens in the full Paryatech workspace.")), []);
  const navigate = (next: PageId, subview?: string) => { setPage(next); if (next === "transactions") setTransactionView(subview || "Register"); setDetail(null); };
  const openRecord = (kind: RecordType, id?: string) => { setDetail(null); setRecord({ kind, id }); };
  const decideReceipt = (decision: "verified" | "rejected") => {
    setReceiptDecision(decision); setDetail(null);
    const now = new Date().toISOString();
    setNewActivity((current) => [{ id: "EVT-PREVIEW-" + Date.now(), event: decision === "verified" ? "Existing receipt verified and applied" : "Receipt proof rejected", category: "Verification", occurredAt: now, recordedAt: now, actor: "Vrushabh Jain", recordId: "RCPT-2026-0088", party: "Kapoor Group", context: "BK-2026-000018 · INV-2026-0079", detail: decision === "verified" ? "The original ₹12,000 receipt was verified and applied. Outstanding decreased from ₹92,000 to ₹80,000; no second receipt was created." : "The proof was rejected. The original receipt remains recorded for review; ₹12,000 remains overdue and outstanding." }, ...current]);
    setToast(decision === "verified" ? "Existing receipt verified and applied. Outstanding is now ₹80,000." : "Proof rejected. ₹12,000 remains overdue.");
  };
  const saveRecord = (money: MoneyRecord, event: ActivityEvent) => { setNewTransactions((rows) => [money, ...rows]); setNewActivity((rows) => [event, ...rows]); setRecord(null); setToast(money.id + " recorded for verification. Balances are unchanged."); };
  const content = page === "overview" ? <Overview obligations={obligations} activity={activity} receiptDecision={receiptDecision} open={setDetail} navigate={navigate} /> : page === "receivables" ? <Receivables obligations={obligations} receiptDecision={receiptDecision} open={setDetail} onRecord={openRecord} /> : page === "payables" ? <Payables obligations={obligations} open={setDetail} onRecord={openRecord} /> : page === "transactions" ? <Transactions key={transactionView} rows={transactions} activity={activity} open={setDetail} onRecord={openRecord} initialView={transactionView} /> : page === "expenses" ? <Expenses rows={EXPENSES} open={setDetail} onRecord={openRecord} /> : page === "bank" ? <Bank open={setDetail} /> : page === "reports" ? <Reports obligations={obligations} transactions={transactions} expenses={EXPENSES} receiptDecision={receiptDecision} open={setDetail} /> : <Controls open={setDetail} navigate={navigate} receiptDecision={receiptDecision} />;
  return <AppShell variant="detail" brandName="" brandMark={<><img className="app-brand-logo app-brand-logo--full" src="/brand/paryatech-lockup.png" alt="Paryatech" /><img className="app-brand-logo app-brand-logo--compact" src="/brand/paryatech-mark.png" alt="Paryatech" /></>} brandAction={<IconChevronRight size={13} />} navGroups={navGroups} notes={{ label: "Finance notes", badge: notes.length, onOpen: () => setNotesOpen(true), onAdd: () => setNotesOpen(true) }} credits={{ remaining: 720, total: 1000, onUpgrade: () => setToast("Upgrade options open in the full Paryatech workspace.") }} onBack={() => setToast("Workspace Home opens in the full Paryatech workspace.")} backLabel="Back to workspace" crumbs={<ol className="app-shell-crumbs__list"><li>Workspace</li><li aria-hidden="true">›</li><li aria-current="page">Finance</li></ol>} search={{ placeholder: "Search anything", "aria-label": "Search the workspace" }} actions={<><IconButton label="Help and support" onClick={() => setToast("Help opens in the full Paryatech workspace.")}><IconHelp size={16} /></IconButton><Tooltip tip="Notifications"><IconButton label="Notifications" onClick={() => setToast("No new finance notifications.")}><IconBell size={16} /></IconButton></Tooltip></>} account={{ name: "Vrushabh Jain", initials: "VJ", tone: "pink", onClick: () => setToast("Account settings open in the full Paryatech workspace.") }}>
    <main id="main-content" className="finance-page"><header className="finance-page-head"><div><h1>{page === "overview" ? "Finance" : PAGE_LABELS[page]}</h1><p>{PAGE_DESCRIPTIONS[page]}</p></div><div className="finance-page-head__actions">{page === "overview" ? <Button variant="brand" size="sm" onClick={() => navigate("transactions", "Activity")}><IconReceipt size={15} />Activity</Button> : null}{["overview", "receivables", "payables", "transactions", "expenses"].includes(page) ? <Button variant="primary" size="sm" onClick={() => openRecord(page === "payables" ? "Supplier payment" : page === "expenses" ? "Agency payment" : "Receipt")}><IconPlus size={15} />{page === "receivables" ? "Record receipt" : page === "payables" ? "Record payment" : page === "expenses" ? "Record reimbursement" : "Record money"}</Button> : null}</div></header><nav className="finance-subnav" aria-label="Finance destinations">{(Object.keys(PAGE_LABELS) as PageId[]).map((id) => <button key={id} type="button" className={page === id ? "active" : ""} onClick={() => navigate(id)}>{PAGE_LABELS[id]}</button>)}</nav><div className="finance-content">{content}</div></main>
    {notesOpen ? <div className="drawer-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) setNotesOpen(false); }}><aside className="finance-notes-panel" role="dialog" aria-modal="true" aria-labelledby="finance-notes-title"><header><div><span>Workspace notes</span><h2 id="finance-notes-title">Finance notes</h2></div><IconButton label="Close notes" onClick={() => setNotesOpen(false)}><IconClose /></IconButton></header><div className="finance-notes-panel__body">{notes.length ? notes.map((note, index) => <article key={index}>{note}<small>Local preview note</small></article>) : <p>No finance notes yet. Add a note for this workspace.</p>}<form onSubmit={(event) => { event.preventDefault(); if (!noteDraft.trim()) return; setNotes((current) => [noteDraft.trim(), ...current]); setNoteDraft(""); }}><label htmlFor="finance-note-draft">New note</label><textarea id="finance-note-draft" value={noteDraft} onChange={(event) => setNoteDraft(event.target.value)} rows={4} placeholder="Write a finance note" /><Button variant="primary" size="sm" type="submit">Add note</Button></form></div></aside></div> : null}
    <DetailPanel detail={detail} obligations={obligations} transactions={transactions} expenses={EXPENSES} activity={activity} receiptDecision={receiptDecision} onClose={() => setDetail(null)} onRecord={openRecord} onReceiptDecision={decideReceipt} open={setDetail} />
    <RecordPanel key={(record?.kind || "closed") + (record?.id || "")} kind={record?.kind || null} obligationId={record?.id} obligations={obligations} transactions={transactions} onClose={() => setRecord(null)} onSave={saveRecord} />
    {toast ? <div className="toast" role="status"><IconCheck size={16} />{toast}<button aria-label="Dismiss message" onClick={() => setToast("")}><IconClose size={13} /></button></div> : null}
  </AppShell>;
}
