import { useState } from "react";
import { readVehicleOfferings } from "../data/vehicleOfferings";
import { formatMoney } from "../rateCard/cards";
import { calculatePrivateTransportQuote, localPackageOptions, resolvePrivateTransportDays, suggestVehicleArrangements, TRANSPORT_TEMPLATE_LABELS, validatePrivateTransportTariff, type PrivateTransportCharge, type PrivateTransportTariff, type PrivateTransportTrip } from "../rateCard/privateTransport";
import { readSupplierTaxProfiles } from "../rateCard/supplierTax";
import type { RateCardDetail } from "../rateCard/types";
import "./RegionalTransportWorkbook.css";
import "./PrivateTransportWorkspace.css";

const asNumber = (value: string): number | null => value === "" ? null : Number(value);
const money = (value: number | null | undefined, currency: string) => value == null ? "—" : formatMoney(value, currency);

function Section({ title: label, action, children }: { title: string; action?: React.ReactNode; children: React.ReactNode }) {
  return <section className="rtw-section"><div className="rtw-section__head"><h2>{label}</h2>{action}</div>{children}</section>;
}

export function PrivateTransportRates({ card, editing, onChange }: { card: RateCardDetail; editing: boolean; onChange: (tariff: PrivateTransportTariff) => void }) {
  const tariff = card.privateTransport!;
  const [activationErrors, setActivationErrors] = useState<string[]>([]);
  const taxProfiles = readSupplierTaxProfiles();
  const availableVehicles = readVehicleOfferings().filter((vehicle) => vehicle.vendorId === tariff.vendorId && vehicle.serviceIds.includes(tariff.serviceId));
  const vehicles = availableVehicles.filter((vehicle) => tariff.vehicleIds.includes(vehicle.id));
  const patch = (update: Partial<PrivateTransportTariff>) => onChange({ ...tariff, ...update });
  const numberCell = (value: number | null | undefined, label: string, update: (value: number | null) => void, isMoney = true) => editing ? <input className="rtw-input rtw-input--number" aria-label={label} type="number" min="0" value={value ?? ""} onChange={(event) => update(asNumber(event.target.value))} /> : <span className="rtw-money">{isMoney ? money(value, card.currency) : value ?? "—"}</span>;
  const updateRoute = (routeId: string, update: Partial<PrivateTransportTariff["routes"][number]>) => patch({ routes: tariff.routes.map((route) => route.id === routeId ? { ...route, ...update } : route) });
  const updatePackage = (packageId: string, update: Partial<PrivateTransportTariff["packages"][number]>) => patch({ packages: tariff.packages.map((pkg) => pkg.id === packageId ? { ...pkg, ...update } : pkg) });
  const updateCharge = (chargeId: string, update: Partial<PrivateTransportCharge>) => patch({ charges: tariff.charges.map((charge) => charge.id === chargeId ? { ...charge, ...update } : charge) });
  const editText = (value: string, label: string, update: (value: string) => void) => editing ? <input className="rtw-input" aria-label={label} value={value} onChange={(event) => update(event.target.value)} /> : value || "—";
  const editSelect = <T extends string>(value: T | null, label: string, options: Array<[NoInfer<T>, string]>, update: (value: T) => void) => editing ? <select className="rtw-input" aria-label={label} value={value ?? ""} onChange={(event) => update(event.target.value as T)}>{options.map(([option, text]) => <option key={option} value={option}>{text}</option>)}</select> : options.find(([option]) => option === value)?.[1] || value || "—";
  const setStatus = (status: PrivateTransportTariff["status"]) => {
    if (status === "Active") {
      const issues = validatePrivateTransportTariff(tariff);
      if (issues.length) { setActivationErrors(issues); return; }
    }
    setActivationErrors([]);
    patch({ status });
  };

  return <div className="rtw-workbook private-transport">
    <Section title="Rate-card information"><div className="private-transport__facts">
      <div><span>Vendor</span><strong>{card.vendor}</strong></div><div><span>Transport service</span><strong>{card.property}</strong></div><div><span>Pricing template</span><strong>{TRANSPORT_TEMPLATE_LABELS[tariff.template]}</strong></div>
      <div><span>Currency</span><strong>{card.currency}</strong></div><div><span>Valid from</span>{editing ? <input type="date" className="rtw-input" value={tariff.validFrom} onChange={(event) => patch({ validFrom: event.target.value })} /> : <strong>{tariff.validFrom}</strong>}</div><div><span>Valid until</span>{editing ? <input type="date" className="rtw-input" value={tariff.validTo} onChange={(event) => patch({ validTo: event.target.value })} /> : <strong>{tariff.validTo}</strong>}</div>
    </div>{tariff.illustrative ? <p className="rtw-table-foot">Illustrative demo prices. Verify the tariff with the vendor before using it in a proposal.</p> : null}{editing ? <div className="private-transport__edit-review"><label><input type="checkbox" checked={tariff.sourceConfirmed} onChange={(event) => patch({ sourceConfirmed: event.target.checked, illustrative: event.target.checked ? false : tariff.illustrative })} /> Tariff verified with vendor</label><label><span>Status</span>{editSelect(tariff.status, "Rate-card status", [["Draft", "Draft"], ["Review", "Review"], ["Active", "Active"]], setStatus)}</label></div> : null}{editing && activationErrors.length ? <div className="private-transport__activation-errors" role="alert"><strong>Complete these details to activate</strong><ul>{activationErrors.map((issue) => <li key={issue}>{issue}</li>)}</ul></div> : null}</Section>

    {editing ? <div className="private-transport__vehicle-pick"><span>Vehicle offerings used by this card</span><div>{availableVehicles.map((vehicle) => <label key={vehicle.id}><input type="checkbox" checked={tariff.vehicleIds.includes(vehicle.id)} onChange={(event) => patch({ vehicleIds: event.target.checked ? [...tariff.vehicleIds, vehicle.id] : tariff.vehicleIds.filter((id) => id !== vehicle.id) })} />{vehicle.label}</label>)}</div>{availableVehicles.length === 0 ? <small>Add a Vehicle Offering under this vendor's transport service first.</small> : null}</div> : null}

    {tariff.template === "fixed-transfer" ? <Section title="Fixed-transfer prices" action={editing ? <button type="button" className="rtw-button" onClick={() => patch({ routes: [...tariff.routes, { id: `route-${Date.now()}`, from: "", to: "", prices: Object.fromEntries(tariff.vehicleIds.map((id) => [id, null])) }] })}>Add route</button> : undefined}><div className="rtw-scroll"><table className="rtw-table"><thead><tr><th>Route</th>{vehicles.map((vehicle) => <th key={vehicle.id}>{vehicle.label}</th>)}{editing ? <th>Action</th> : null}</tr></thead><tbody>{tariff.routes.map((route) => <tr key={route.id}><th scope="row"><div className="private-transport__route">{editText(route.from, "Route origin", (from) => updateRoute(route.id, { from }))}<span aria-hidden="true">→</span>{editText(route.to, "Route destination", (to) => updateRoute(route.id, { to }))}</div></th>{vehicles.map((vehicle) => <td key={vehicle.id}>{numberCell(route.prices[vehicle.id], `${route.from} to ${route.to}, ${vehicle.label} price`, (amount) => updateRoute(route.id, { prices: { ...route.prices, [vehicle.id]: amount } }))}</td>)}{editing ? <td><button type="button" className="rtw-button" onClick={() => patch({ routes: tariff.routes.filter((item) => item.id !== route.id) })}>Remove</button></td> : null}</tr>)}</tbody></table></div></Section> : null}

    {tariff.template === "local-package" ? <Section title="Local-package prices" action={editing ? <button type="button" className="rtw-button" onClick={() => { const id = `package-${Date.now()}`; patch({ packages: [...tariff.packages, { id, name: "New package", hours: 0, km: 0 }], packagePrices: Object.fromEntries(tariff.vehicleIds.map((vehicleId) => [vehicleId, { ...tariff.packagePrices[vehicleId], [id]: null }])) }); }}>Add package</button> : undefined}><div className="rtw-scroll"><table className="rtw-table"><thead><tr><th>Vehicle</th>{tariff.packages.map((pkg) => <th key={pkg.id}><div className="private-transport__package-head">{editText(pkg.name, "Package name", (name) => updatePackage(pkg.id, { name }))}{editing ? <span>{numberCell(pkg.hours, `${pkg.name} included hours`, (hours) => updatePackage(pkg.id, { hours: hours ?? 0 }), false)} hr / {numberCell(pkg.km, `${pkg.name} included km`, (km) => updatePackage(pkg.id, { km: km ?? 0 }), false)} km <button type="button" className="private-transport__remove" onClick={() => patch({ packages: tariff.packages.filter((item) => item.id !== pkg.id) })} aria-label={`Remove ${pkg.name}`}>×</button></span> : null}</div></th>)}</tr></thead><tbody>{vehicles.map((vehicle) => <tr key={vehicle.id}><th scope="row">{vehicle.label}</th>{tariff.packages.map((pkg) => <td key={pkg.id}>{numberCell(tariff.packagePrices[vehicle.id]?.[pkg.id], `${vehicle.label} ${pkg.name} price`, (amount) => patch({ packagePrices: { ...tariff.packagePrices, [vehicle.id]: { ...tariff.packagePrices[vehicle.id], [pkg.id]: amount } } }))}</td>)}</tr>)}</tbody></table></div></Section> : null}

    {tariff.template === "outstation-km" ? <Section title="Outstation kilometre prices"><div className="rtw-scroll"><table className="rtw-table"><thead><tr><th>Vehicle</th><th>Rate / km</th><th>Minimum km / day</th><th>Driver / day</th></tr></thead><tbody>{vehicles.map((vehicle) => { const row = tariff.outstationPrices[vehicle.id]; const update = (key: keyof typeof row, value: number | null) => patch({ outstationPrices: { ...tariff.outstationPrices, [vehicle.id]: { ...row, [key]: value } } }); return <tr key={vehicle.id}><th scope="row">{vehicle.label}</th><td>{numberCell(row?.ratePerKm, `${vehicle.label} rate per km`, (value) => update("ratePerKm", value))}</td><td>{numberCell(row?.minKmPerDay, `${vehicle.label} minimum km per day`, (value) => update("minKmPerDay", value), false)}</td><td>{numberCell(row?.driverPerDay, `${vehicle.label} driver per day`, (value) => update("driverPerDay", value))}</td></tr>; })}</tbody></table></div></Section> : null}

    {tariff.template === "daily-hire" ? <Section title="Daily-hire prices"><div className="rtw-scroll"><table className="rtw-table"><thead><tr><th>Vehicle</th><th>Price / day</th><th>Included km / day</th><th>Included hours / day</th></tr></thead><tbody>{vehicles.map((vehicle) => { const row = tariff.dailyPrices[vehicle.id]; const update = (key: keyof typeof row, value: number | null) => patch({ dailyPrices: { ...tariff.dailyPrices, [vehicle.id]: { ...row, [key]: value } } }); return <tr key={vehicle.id}><th scope="row">{vehicle.label}</th><td>{numberCell(row?.pricePerDay, `${vehicle.label} price per day`, (value) => update("pricePerDay", value))}</td><td>{numberCell(row?.includedKmPerDay, `${vehicle.label} included km per day`, (value) => update("includedKmPerDay", value), false)}</td><td>{numberCell(row?.includedHoursPerDay, `${vehicle.label} included hours per day`, (value) => update("includedHoursPerDay", value), false)}</td></tr>; })}</tbody></table></div></Section> : null}

    {tariff.template === "local-package" || tariff.template === "daily-hire" ? <Section title="Excess usage"><div className="rtw-scroll"><table className="rtw-table"><thead><tr><th>Vehicle</th><th>Extra km</th><th>Extra hour</th></tr></thead><tbody>{vehicles.map((vehicle) => { const row = tariff.excessPrices[vehicle.id]; return <tr key={vehicle.id}><th scope="row">{vehicle.label}</th><td>{numberCell(row?.extraKm, `${vehicle.label} extra km`, (value) => patch({ excessPrices: { ...tariff.excessPrices, [vehicle.id]: { ...row, extraKm: value } } }))}</td><td>{numberCell(row?.extraHour, `${vehicle.label} extra hour`, (value) => patch({ excessPrices: { ...tariff.excessPrices, [vehicle.id]: { ...row, extraHour: value } } }))}</td></tr>; })}</tbody></table></div></Section> : null}

    {tariff.template !== "fixed-transfer" ? <Section title="Pricing rules"><div className="private-transport__rules"><label><span>Operating places</span>{editText((tariff.coverageAreas ?? []).join(", "), "Operating places", (value) => patch({ coverageAreas: value.split(",").map((place) => place.trim()).filter(Boolean) }))}</label>
      {tariff.template === "outstation-km" ? <><label><span>Minimum calculation</span>{editSelect(tariff.rules.minimumMethod ?? "unknown", "Minimum calculation", [["unknown", "Select minimum method"], ["pooled", "Pooled across hire"], ["daily", "Each day"], ["none", "No minimum"]], (minimumMethod) => patch({ rules: { ...tariff.rules, minimumMethod: minimumMethod === "unknown" ? null : minimumMethod } }))}</label>{tariff.rules.minimumMethod === "daily" && ((tariff.rules.garageKm ?? 0) > 0 || (tariff.rules.emptyReturnKm ?? 0) > 0) ? <label><span>Garage / return km and daily minimum</span>{editSelect(tariff.rules.dailyExtraKmTreatment ?? "unknown", "Garage and return km treatment", [["unknown", "Select rule"], ["within-minimum", "Count within each daily minimum"], ["after-minimum", "Charge after each daily minimum"]], (dailyExtraKmTreatment) => patch({ rules: { ...tariff.rules, dailyExtraKmTreatment: dailyExtraKmTreatment === "unknown" ? null : dailyExtraKmTreatment } }))}</label> : null}<label><span>Distance measured</span>{editText(tariff.rules.distanceBasis, "Distance measured", (distanceBasis) => patch({ rules: { ...tariff.rules, distanceBasis } }))}</label><label><span>Billable days</span>{editSelect(tariff.rules.billableDayMethod ?? "unknown", "Billable days", [["unknown", "Select day rule"], ["calendar", "Calendar service dates"], ["24-hour", "24-hour periods"]], (billableDayMethod) => patch({ rules: { ...tariff.rules, billableDayMethod: billableDayMethod === "unknown" ? null : billableDayMethod } }))}</label><label><span>Timezone</span>{editText(tariff.rules.timezone, "Pricing timezone", (timezone) => patch({ rules: { ...tariff.rules, timezone } }))}</label><label><span>Garage kilometres</span>{numberCell(tariff.rules.garageKm, "Garage kilometres", (garageKm) => patch({ rules: { ...tariff.rules, garageKm } }), false)}</label><label><span>Empty-return kilometres</span>{numberCell(tariff.rules.emptyReturnKm, "Empty-return kilometres", (emptyReturnKm) => patch({ rules: { ...tariff.rules, emptyReturnKm } }), false)}</label><label><span>Distance rounding</span>{editSelect(tariff.rules.roundKmUp ? "whole" : "exact", "Distance rounding", [["whole", "Next whole km"], ["exact", "Exact distance"]], (value) => patch({ rules: { ...tariff.rules, roundKmUp: value === "whole" } }))}</label><label><span>Fuel</span>{editSelect(tariff.rules.fuelIncluded == null ? "unknown" : tariff.rules.fuelIncluded ? "yes" : "no", "Fuel", [["unknown", "Select fuel rule"], ["yes", "Included"], ["no", "Separate charge"]], (value) => patch({ rules: { ...tariff.rules, fuelIncluded: value === "unknown" ? null : value === "yes" } }))}</label></> : null}
      {tariff.template === "daily-hire" ? <><label><span>Unused km carry forward</span>{editSelect(tariff.rules.carryUnusedKm == null ? "unknown" : tariff.rules.carryUnusedKm ? "yes" : "no", "Unused km carry forward", [["unknown", "Select rule"], ["no", "No"], ["yes", "Yes"]], (value) => patch({ rules: { ...tariff.rules, carryUnusedKm: value === "unknown" ? null : value === "yes" } }))}</label><label><span>Unused hours carry forward</span>{editSelect(tariff.rules.carryUnusedHours == null ? "unknown" : tariff.rules.carryUnusedHours ? "yes" : "no", "Unused hours carry forward", [["unknown", "Select rule"], ["no", "No"], ["yes", "Yes"]], (value) => patch({ rules: { ...tariff.rules, carryUnusedHours: value === "unknown" ? null : value === "yes" } }))}</label><label><span>Billable days</span>{editSelect(tariff.rules.billableDayMethod ?? "unknown", "Billable days", [["unknown", "Select day rule"], ["calendar", "Calendar service dates"], ["24-hour", "24-hour periods"]], (billableDayMethod) => patch({ rules: { ...tariff.rules, billableDayMethod: billableDayMethod === "unknown" ? null : billableDayMethod } }))}</label><label><span>Timezone</span>{editText(tariff.rules.timezone, "Pricing timezone", (timezone) => patch({ rules: { ...tariff.rules, timezone } }))}</label></> : null}
      {tariff.template === "local-package" ? <label><span>When km and hours both exceed</span>{editSelect(tariff.rules.excessMethod ?? "unknown", "Excess usage method", [["unknown", "Select charging rule"], ["both", "Charge both"], ["higher", "Charge higher amount"], ["km-only", "Charge kilometres only"], ["hour-only", "Charge hours only"]], (value) => patch({ rules: { ...tariff.rules, excessMethod: value === "unknown" ? null : value } }))}</label> : null}
    </div></Section> : null}

    <Section title="Additional charges" action={editing ? <button type="button" className="rtw-button" onClick={() => patch({ charges: [...tariff.charges, { id: `charge-${Date.now()}`, name: "New charge", appliesTo: "All trips", treatment: "actual", amount: null, chargedPer: "hire", trigger: "always" }] })}>Add charge</button> : undefined}>
      <div className="rtw-scroll"><table className="rtw-table"><thead><tr><th>Charge</th><th>Applies to</th><th>Treatment</th><th>Amount</th><th>Charged per</th><th>Trigger</th>{editing ? <th>Action</th> : null}</tr></thead><tbody>{tariff.charges.map((charge) => <tr key={charge.id}>
        <th scope="row">{editText(charge.name, "Charge name", (name) => updateCharge(charge.id, { name }))}</th>
        <td>{editText(charge.appliesTo, "Applies to", (appliesTo) => updateCharge(charge.id, { appliesTo }))}</td>
        <td>{editSelect(charge.treatment, "Charge treatment", [["included", "Included"], ["fixed", "Fixed"], ["actual", "Actual"], ["not-applicable", "Not applicable"], ["unconfirmed", "Needs supplier answer"]], (treatment) => updateCharge(charge.id, { treatment, amount: treatment === "fixed" ? charge.amount : null }))}</td>
        <td>{charge.treatment === "fixed" ? numberCell(charge.amount, `${charge.name} amount`, (amount) => updateCharge(charge.id, { amount })) : "—"}</td>
        <td>{editSelect(charge.chargedPer, "Charged per", [["hire", "Hire"], ["vehicle", "Vehicle"], ["day", "Vehicle/day"], ["night", "Vehicle/night"], ["hour", "Vehicle/hour"], ["km", "Vehicle/km"]], (chargedPer) => updateCharge(charge.id, { chargedPer }))}</td>
        <td>{editSelect(charge.trigger, "Charge trigger", [["always", "Always"], ["night-pickup", "Night pickup"], ["waiting-over", "Extra waiting"], ["distance-over", "Excess distance"]], (trigger) => updateCharge(charge.id, { trigger, chargedPer: trigger === "waiting-over" ? "hour" : trigger === "distance-over" ? "km" : charge.chargedPer, waitingIncrementMinutes: trigger === "waiting-over" ? charge.waitingIncrementMinutes ?? 60 : charge.waitingIncrementMinutes }))}</td>
        {editing ? <td><button className="rtw-button" type="button" onClick={() => patch({ charges: tariff.charges.filter((item) => item.id !== charge.id) })}>Remove</button></td> : null}
      </tr>)}</tbody></table></div>{tariff.charges.length === 0 ? <div className="rtw-table-foot">No additional charges recorded.</div> : null}
    </Section>

    {editing && tariff.charges.length > 0 ? <Section title="Charge conditions"><div className="private-transport__charge-conditions">{tariff.charges.map((charge) => <div className="private-transport__charge-condition" key={charge.id}><strong>{charge.name}</strong>
      {charge.trigger === "night-pickup" ? <><label><span>From</span><input type="time" className="rtw-input" value={charge.triggerStart ?? ""} onChange={(event) => updateCharge(charge.id, { triggerStart: event.target.value })} /></label><label><span>Until</span><input type="time" className="rtw-input" value={charge.triggerEnd ?? ""} onChange={(event) => updateCharge(charge.id, { triggerEnd: event.target.value })} /></label></> : null}
      {charge.trigger === "waiting-over" ? <><label><span>Included waiting minutes</span>{numberCell(charge.includedWaitingMinutes, `${charge.name} included waiting`, (includedWaitingMinutes) => updateCharge(charge.id, { includedWaitingMinutes: includedWaitingMinutes ?? undefined }), false)}</label><label><span>Bill every minutes</span>{numberCell(charge.waitingIncrementMinutes ?? 60, `${charge.name} billing increment`, (waitingIncrementMinutes) => updateCharge(charge.id, { waitingIncrementMinutes: waitingIncrementMinutes ?? undefined }), false)}</label></> : null}
      {charge.trigger === "distance-over" ? <label><span>Included kilometres</span>{numberCell(charge.includedKm, `${charge.name} included distance`, (includedKm) => updateCharge(charge.id, { includedKm: includedKm ?? undefined }), false)}</label> : null}
      {tariff.template === "fixed-transfer" ? <div className="private-transport__scope"><span>Routes</span>{tariff.routes.map((route) => <label key={route.id}><input type="checkbox" checked={!charge.routeIds?.length || charge.routeIds.includes(route.id)} onChange={(event) => { const current = charge.routeIds?.length ? charge.routeIds : tariff.routes.map((item) => item.id); const next = event.target.checked ? [...new Set([...current, route.id])] : current.filter((id) => id !== route.id); if (next.length) updateCharge(charge.id, { routeIds: next.length === tariff.routes.length ? [] : next }); }} />{route.from} ? {route.to}</label>)}</div> : null}
    </div>)}</div></Section> : null}

    <Section title="Supplier tax"><div className="private-transport__tax-row"><span>Listed supplier prices</span>{editing ? editSelect(tariff.taxMode ?? "unknown", "Supplier price tax treatment", [["unknown", "Not set"], ["inclusive", "Tax included"], ["exclusive", "Tax added separately"]], (taxMode) => patch({ taxMode: taxMode === "unknown" ? null : taxMode })) : <strong>{tariff.taxMode === "inclusive" ? "Tax included" : tariff.taxMode === "exclusive" ? "Tax added separately" : "Not set"}</strong>}</div><div className="private-transport__tax-row"><span>Approved shared supplier tax profile</span>{editing ? <select className="rtw-input" aria-label="Approved supplier tax profile" value={tariff.taxProfileId ?? ""} onChange={(event) => patch({ taxProfileId: event.target.value || null })}><option value="">Select approved profile</option>{taxProfiles.filter((profile) => profile.approved && profile.approvalSource.trim() && profile.recoverable != null).map((profile) => <option value={profile.id} key={profile.id}>{profile.name} · {(profile.rate * 100).toFixed(2)}%</option>)}</select> : <strong>{taxProfiles.find((profile) => profile.id === tariff.taxProfileId && profile.approved)?.name ?? "Not connected"}</strong>}</div><p className="rtw-table-foot">Approved supplier tax profiles and credit treatment are managed in Finance.</p></Section>
  </div>;
}

export function PrivateTransportTest({ card }: { card: RateCardDetail }) {
  const tariff = card.privateTransport!;
  const vehicles = readVehicleOfferings().filter((vehicle) => tariff.vehicleIds.includes(vehicle.id) && vehicle.vendorId === tariff.vendorId && vehicle.serviceIds.includes(tariff.serviceId));
  const firstRoute = tariff.routes[0];
  const [trip, setTrip] = useState<PrivateTransportTrip>(() => ({ date: tariff.validFrom, endDate: tariff.template === "fixed-transfer" || tariff.template === "local-package" ? undefined : tariff.validFrom, pickupTime: "10:00", dropTime: tariff.template === "fixed-transfer" || tariff.template === "local-package" ? undefined : "18:00", pickup: firstRoute?.from || tariff.coverageAreas?.[0] || "Kochi", drop: firstRoute?.to || tariff.coverageAreas?.[0] || "Munnar", routeId: firstRoute?.id || "", packageId: tariff.packages[0]?.id || "", vehicleId: vehicles[0]?.id || "", vehicleAllocations: vehicles[0] ? [{ vehicleId: vehicles[0].id, quantity: 1 }] : [], travellers: 2, guideSeats: 0, mediumBags: 2, largeBags: 0, cabinBags: 0, acRequired: true, vehicleCount: 1, plannedKm: tariff.template === "outstation-km" ? 350 : 40, plannedHours: tariff.template === "daily-hire" ? 10 : 4, waitingMinutes: 0, billableDays: 1, dailyKm: [], dailyHours: [] }));
  const set = <K extends keyof PrivateTransportTrip>(key: K, value: PrivateTransportTrip[K]) => setTrip((current) => ({ ...current, [key]: value }));
  const calculatedDays = resolvePrivateTransportDays(tariff, trip);
  const [packageChoice, setPackageChoice] = useState("suggested");
  const packagesByPrice = localPackageOptions(tariff, trip);
  const selectedPackageId = packageChoice === "suggested" ? packagesByPrice[0]?.id ?? trip.packageId : packageChoice;
  const quote = calculatePrivateTransportQuote(tariff, vehicles, { ...trip, packageId: selectedPackageId }, readSupplierTaxProfiles());
  const suggestedArrangements = suggestVehicleArrangements(vehicles, trip);
  const allocations = trip.vehicleAllocations ?? [];
  const selectedVehicleIds = new Set(allocations.map((item) => item.vehicleId));
  const totalSeats = allocations.reduce((total, item) => total + (vehicles.find((vehicle) => vehicle.id === item.vehicleId)?.passengerSeats ?? 0) * item.quantity, 0);
  const totalBags = allocations.reduce((total, item) => total + (vehicles.find((vehicle) => vehicle.id === item.vehicleId)?.mediumBags ?? 0) * item.quantity, 0);
  const totalLargeBags = allocations.reduce((total, item) => total + (vehicles.find((vehicle) => vehicle.id === item.vehicleId)?.largeBags ?? 0) * item.quantity, 0);
  const totalCabinBags = allocations.reduce((total, item) => total + (vehicles.find((vehicle) => vehicle.id === item.vehicleId)?.cabinBags ?? 0) * item.quantity, 0);
  const totalCombinedBags = allocations.reduce((total, item) => total + (vehicles.find((vehicle) => vehicle.id === item.vehicleId)?.combinedBagUnits ?? 0) * item.quantity, 0);
  const neededCombinedBags = trip.mediumBags + (trip.largeBags ?? 0) * 2 + (trip.cabinBags ?? 0) * 0.5;
  const hasNonAc = trip.acRequired && allocations.some((item) => !vehicles.find((vehicle) => vehicle.id === item.vehicleId)?.airConditioned);
  const routeOrigins = [...new Set(tariff.routes.map((route) => route.from))];
  const routeDestinations = [...new Set(tariff.routes.filter((route) => route.from === trip.pickup).map((route) => route.to))];
  const field = (label: string, key: "travellers" | "guideSeats" | "mediumBags" | "largeBags" | "cabinBags" | "plannedKm" | "plannedHours" | "waitingMinutes" | "billableDays") => <label><span>{label}</span><input type="number" min={key === "travellers" || key === "billableDays" ? 1 : 0} value={trip[key] ?? 0} onChange={(event) => set(key, Number(event.target.value))} /></label>;
  return <div className="rtw-test private-transport-test"><section><div className="rtw-test__head"><h2>Trip details</h2></div><div className="rtw-test__fields">
    <label><span>Requirement</span><input readOnly value={TRANSPORT_TEMPLATE_LABELS[tariff.template]} /></label><label><span>Service date</span><input type="date" value={trip.date} onChange={(event) => setTrip((current) => ({ ...current, date: event.target.value, endDate: current.endDate === current.date ? event.target.value : current.endDate }))} /></label>
    {tariff.template === "fixed-transfer" ? <>
      <label><span>Pickup</span><select value={trip.pickup} onChange={(event) => { const nextRoute = tariff.routes.find((route) => route.from === event.target.value); setTrip((current) => ({ ...current, pickup: nextRoute?.from ?? "", drop: nextRoute?.to ?? "", routeId: nextRoute?.id ?? "" })); }}><option value="">Choose pickup</option>{routeOrigins.map((place) => <option key={place} value={place}>{place}</option>)}</select></label>
      <label><span>Final drop</span><select value={trip.drop} onChange={(event) => { const nextRoute = tariff.routes.find((route) => route.from === trip.pickup && route.to === event.target.value); setTrip((current) => ({ ...current, drop: nextRoute?.to ?? "", routeId: nextRoute?.id ?? "" })); }}><option value="">Choose final drop</option>{routeDestinations.map((place) => <option key={place} value={place}>{place}</option>)}</select></label>
    </> : <><label><span>Pickup</span><input value={trip.pickup} onChange={(event) => set("pickup", event.target.value)} /></label><label><span>Final drop</span><input value={trip.drop} onChange={(event) => set("drop", event.target.value)} /></label></>}
    <label><span>Pickup time</span><input type="time" value={trip.pickupTime} onChange={(event) => set("pickupTime", event.target.value)} /></label>
    {tariff.template === "local-package" ? <label><span>Local package</span><select value={packageChoice} onChange={(event) => setPackageChoice(event.target.value)}><option value="suggested">Suggested · {packagesByPrice[0]?.name ?? "choose usage"}</option>{packagesByPrice.map((pkg) => <option key={pkg.id} value={pkg.id}>{pkg.name} · {money(pkg.amount, card.currency)} incl. planned excess</option>)}</select></label> : null}
    {tariff.template === "outstation-km" || tariff.template === "daily-hire" ? <><label><span>Final service date</span><input type="date" value={trip.endDate || ""} onChange={(event) => set("endDate", event.target.value)} /></label><label><span>Final drop time</span><input type="time" value={trip.dropTime || ""} onChange={(event) => set("dropTime", event.target.value)} /></label></> : null}
    {field("Travellers", "travellers")}{field("Guide / staff seats", "guideSeats")}{field("Medium bags", "mediumBags")}{field("Large suitcases", "largeBags")}{field("Cabin bags", "cabinBags")}
    <label><span>Air conditioning</span><select value={trip.acRequired ? "required" : "any"} onChange={(event) => set("acRequired", event.target.value === "required")}><option value="required">AC required</option><option value="any">Any</option></select></label>
    <div className="rtw-test__wide private-transport-test__fleet"><div className="private-transport-test__fleet-head"><strong>Vehicles</strong><button type="button" className="rtw-button" disabled={selectedVehicleIds.size >= vehicles.length} onClick={() => { const next = vehicles.find((vehicle) => !selectedVehicleIds.has(vehicle.id)); if (next) set("vehicleAllocations", [...allocations, { vehicleId: next.id, quantity: 1 }]); }}>Add vehicle</button></div>
      {suggestedArrangements.length ? <div className="private-transport-test__suggestions"><span>Suitable arrangements</span>{suggestedArrangements.slice(0, 6).map((arrangement) => <button type="button" key={arrangement.map((row) => `${row.vehicleId}:${row.quantity}`).join("+")} onClick={() => set("vehicleAllocations", arrangement)}>{arrangement.map((row) => `${row.quantity} ${vehicles.find((vehicle) => vehicle.id === row.vehicleId)?.label ?? "vehicle"}`).join(" + ")}</button>)}</div> : <p className="private-transport-test__no-fleet">No confirmed vehicle combination fits these travellers, bags and AC preference.</p>}
      {allocations.map((allocation, index) => <div className="private-transport-test__fleet-row" key={`${allocation.vehicleId}-${index}`}><label><span>Vehicle offering</span><select value={allocation.vehicleId} onChange={(event) => set("vehicleAllocations", allocations.map((row, rowIndex) => rowIndex === index ? { ...row, vehicleId: event.target.value } : row))}>{vehicles.filter((vehicle) => vehicle.id === allocation.vehicleId || !selectedVehicleIds.has(vehicle.id)).map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.label} · {vehicle.passengerSeats ?? "?"} seats · {vehicle.mediumBags ?? "?"} bags</option>)}</select></label><label><span>Quantity</span><input type="number" min="1" step="1" value={allocation.quantity} onChange={(event) => set("vehicleAllocations", allocations.map((row, rowIndex) => rowIndex === index ? { ...row, quantity: Number(event.target.value) } : row))} /></label><button type="button" className="private-transport-test__remove-vehicle" onClick={() => set("vehicleAllocations", allocations.filter((_, rowIndex) => rowIndex !== index))}>Remove</button></div>)}
    </div>
    {tariff.template !== "fixed-transfer" || tariff.charges.some((charge) => charge.trigger === "distance-over") ? field("Planned kilometres", "plannedKm") : null}{tariff.template === "local-package" || tariff.template === "daily-hire" ? field("Planned hours", "plannedHours") : null}{tariff.charges.some((charge) => charge.trigger === "waiting-over") ? field("Waiting minutes", "waitingMinutes") : null}{tariff.template === "outstation-km" || tariff.template === "daily-hire" ? <label><span>Billable days</span><input readOnly value={calculatedDays ?? "Set service dates"} /></label> : null}
    {(tariff.template === "daily-hire" || tariff.template === "outstation-km" && tariff.rules.minimumMethod === "daily") && (calculatedDays ?? 1) > 1 ? <div className="rtw-test__wide private-transport-test__days">{Array.from({ length: Math.min(31, calculatedDays ?? 1) }, (_, index) => <div key={index}><strong>Day {index + 1}</strong><label><span>Kilometres</span><input type="number" min="0" value={trip.dailyKm[index] ?? ""} onChange={(event) => set("dailyKm", Array.from({ length: calculatedDays ?? 1 }, (_, i) => i === index ? Number(event.target.value) : trip.dailyKm[i] ?? 0))} /></label>{tariff.template === "daily-hire" ? <label><span>Hours</span><input type="number" min="0" value={trip.dailyHours[index] ?? ""} onChange={(event) => set("dailyHours", Array.from({ length: calculatedDays ?? 1 }, (_, i) => i === index ? Number(event.target.value) : trip.dailyHours[i] ?? 0))} /></label> : null}</div>)}</div> : null}
  </div><div className="rtw-test__capacity">Selected: <strong>{totalSeats} seats</strong> · {totalBags} medium, {totalLargeBags} large, {totalCabinBags} cabin bags · {totalCombinedBags} combined luggage units. Needed: {trip.travellers + trip.guideSeats} seats · {trip.mediumBags} medium, {trip.largeBags ?? 0} large, {trip.cabinBags ?? 0} cabin bags · {neededCombinedBags} combined luggage units{trip.acRequired ? " · AC" : ""}. {totalSeats < trip.travellers + trip.guideSeats || totalBags < trip.mediumBags || totalLargeBags < (trip.largeBags ?? 0) || totalCabinBags < (trip.cabinBags ?? 0) || totalCombinedBags < neededCombinedBags || hasNonAc ? <strong> Choose another vehicle or add one.</strong> : null} A rate does not reserve a vehicle.</div></section>
  <section><div className="rtw-test__head"><h2>Supplier calculation</h2></div><div className="rtw-test__total"><span>{tariff.taxMode === "inclusive" ? "Supplier amount including tax" : tariff.taxMode === "exclusive" ? "Supplier amount before tax" : "Supplier amount"}</span><strong>{money(quote.commercialAmount, card.currency)}</strong><small>{!tariff.sourceConfirmed || tariff.status !== "Active" ? "Illustrative calculation · supplier confirmation pending" : quote.quoteBasis === "base-plus-actuals" ? "Known base plus actual charges" : quote.quoteBasis === "unpriced" ? "Needs review" : "Fixed for the entered scope"}</small></div><div className="rtw-test__breakdown">{[["Base vehicle tariff", quote.base], ["Driver allowance", quote.driver], ["Excess usage", quote.excess], ["Fixed additional charges", quote.fixedExtras]].map(([label, value]) => <div key={String(label)}><span>{label}</span><strong>{money(value as number | null, card.currency)}</strong></div>)}<div><span>Supplier tax</span><strong>{quote.supplierTax == null ? tariff.taxMode === "inclusive" ? "Included; breakdown pending profile" : "Pending approved profile" : tariff.taxMode === "inclusive" ? `${money(quote.supplierTax, card.currency)} included` : money(quote.supplierTax, card.currency)}</strong></div><div className="rtw-test__payable"><span>Supplier payable</span><strong>{quote.commercialAmount == null ? "Unpriced" : quote.actualCharges.length ? "Pending actual charges" : quote.supplierPayable == null ? "Pending tax or approval" : money(quote.supplierPayable, card.currency)}</strong></div></div>{quote.billableKm != null ? <p className="rtw-test__actuals">Billable distance: {quote.billableKm} km. Planned chargeable distance: {trip.plannedKm} km. The supplier minimum and distance rule determine the difference.</p> : null}{quote.vehicleLines?.length ? <div className="private-transport-test__vehicle-lines">{quote.vehicleLines.map((line) => <div key={line.vehicleId}><span>{line.quantity} × {vehicles.find((vehicle) => vehicle.id === line.vehicleId)?.label ?? "Vehicle"}</span><strong>{money(line.base == null ? null : line.base + (line.driver ?? 0) + (line.excess ?? 0) + (line.fixedExtras ?? 0), card.currency)}</strong></div>)}</div> : null}{quote.actualCharges.length ? <p className="rtw-test__actuals">Payable at actuals: {quote.actualCharges.join(", ")}. This is not a fixed all-inclusive total.</p> : null}{quote.blockers.length ? <div className="rtw-test__review"><h3>Needs review</h3><ul>{quote.blockers.map((blocker) => <li key={blocker}>{blocker}</li>)}</ul></div> : null}</section>
  </div>;
}
