import { Icon } from "@paryatech/ui";
import type { ProposalService, StayChild } from "./proposalModel";
import { availableAccommodationCards, availableTransportCards, serviceCostBreakdown, type CostBreakdown } from "./serviceCosting";
import "./PackageStructuredPricing.css";

const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
const number = (value: string) => value === "" ? undefined : Number(value);
type Props = { service: ProposalService; dayIndex: number; onChange: (patch: Partial<ProposalService>) => void };

function Quote({ quote }: { quote: CostBreakdown }) {
  return <div className="package-structured__quote"><div><span>Supplier cost</span><strong>{quote.status === "priced" ? money.format(quote.total) : quote.status === "included" ? "Included" : "To confirm"}</strong></div>{quote.source ? <small>{quote.source}</small> : null}{quote.issue ? <p role="status">{quote.issue}</p> : quote.lines.length ? <div className="package-structured__lines">{quote.lines.map((line, index) => <div key={`${line.label}-${index}`}><span><strong>{line.label}</strong><small>{line.basis}</small></span><strong>{money.format(line.amount)}</strong></div>)}</div> : null}</div>;
}

function CommonStatus({ service, onChange }: Pick<Props, "service" | "onChange">) {
  return <div className="package-structured__status"><label><span>Pricing status</span>{service.rateCardId ? <output>Calculated from published CRM card</output> : <select value={service.priceState ?? "unpriced"} onChange={(event) => onChange({ priceState: event.target.value as ProposalService["priceState"] })}><option value="unpriced">Rate to confirm</option><option value="priced">Supplier rate confirmed</option><option value="included">Included at no charge</option></select>}</label><label className="package-structured__optional"><input type="checkbox" checked={Boolean(service.optional)} onChange={(event) => onChange({ optional: event.target.checked })} /> Optional extra</label></div>;
}

function Accommodation({ service, dayIndex, onChange }: Props) {
  const cards = availableAccommodationCards.filter((card) => card.property.trim().toLowerCase() === service.title.trim().toLowerCase());
  const card = cards.find((item) => item.id === service.rateCardId);
  const quote = serviceCostBreakdown(service, { dayIndex });
  const roomIndex = card?.rooms.findIndex((room) => room.id === service.roomTypeId) ?? -1;
  const mealIndex = card?.meals.findIndex((meal) => meal.code === service.mealPlanCode) ?? -1;
  const children = service.stayChildren ?? [];
  const setChild = (index: number, change: Partial<StayChild>) => onChange({ stayChildren: children.map((item, i) => i === index ? { ...item, ...change } : item) });
  return <section className="package-structured" aria-label={`${service.title} accommodation costing`}>
    <header><span className="package-structured__icon"><Icon name="hotel" size="sm" /></span><div><small>Day {dayIndex + 1} · Accommodation</small><h3>{service.title}</h3><span>{service.vendor ?? "Choose a vendor rate card"}</span></div><strong>{quote.status === "priced" ? money.format(quote.total) : quote.status === "included" ? "Included" : "Unpriced"}</strong></header>
    <div className="package-structured__body"><div className="package-structured__intro"><strong>Stay and room rate</strong><p>Choose the published card for this property. Room, meal, season, guest rules and mandatory supplements come from Vendor CRM.</p></div>
      <div className="package-structured__grid"><label className="package-structured__wide"><span>Vendor rate card</span><select value={card?.id ?? ""} onChange={(event) => { const next = cards.find((item) => item.id === event.target.value); onChange({ rateCardId: next?.id, vendor: next?.vendor ?? service.vendor, roomTypeId: next?.rooms[0]?.id, mealPlanCode: next?.meals[0]?.code, priceState: next ? "priced" : "unpriced", cost: undefined }); }}><option value="">Manual supplier quote / no matching card</option>{cards.map((item) => <option value={item.id} key={item.id}>{item.vendor} · {item.name} · {item.validity}</option>)}</select></label>
      {card ? <><div className="package-structured__card-note"><strong>{card.ref}</strong><span>{card.validity} · {card.mealBasis}</span></div><label><span>Room type</span><select value={service.roomTypeId ?? ""} onChange={(event) => onChange({ roomTypeId: event.target.value })}>{card.rooms.map((room) => <option value={room.id} key={room.id}>{room.name} · {room.baseOccupancy} included, max {room.maxOccupancy}</option>)}</select></label><label><span>Meal plan</span><select value={service.mealPlanCode ?? ""} onChange={(event) => onChange({ mealPlanCode: event.target.value })}>{card.meals.map((meal) => <option value={meal.code} key={meal.code}>{meal.code} · {meal.label}</option>)}</select></label></> : <><div className="package-structured__card-note"><strong>{cards.length ? "Select a matching published card" : "No matching published card"}</strong><span>Manual quotes stay separate from the CRM season matrix.</span></div><label><span>Supplier</span><input value={service.vendor ?? ""} onChange={(event) => onChange({ vendor: event.target.value })} placeholder="Confirm supplier" /></label><label><span>Meal plan / quote scope</span><input value={service.mealPlan ?? ""} onChange={(event) => onChange({ mealPlan: event.target.value })} placeholder="e.g. Breakfast included" /></label><label><span>Quoted rate per room night (₹)</span><input type="number" min="0" value={service.cost ?? ""} onChange={(event) => onChange({ cost: number(event.target.value) })} placeholder="Confirmed supplier rate" /></label></>}
      <label><span>Pricing reference check-in</span><input type="date" value={service.stayCheckIn ?? ""} onChange={(event) => onChange({ stayCheckIn: event.target.value })} /></label><label><span>Nights</span><input type="number" min="1" value={service.nights ?? 1} onChange={(event) => onChange({ nights: number(event.target.value) })} /></label><label><span>Rooms</span><input type="number" min="1" value={service.rooms ?? 1} onChange={(event) => onChange({ rooms: number(event.target.value) })} /></label><label><span>Adults staying</span><input type="number" min="0" value={service.stayAdults ?? 2} onChange={(event) => onChange({ stayAdults: number(event.target.value) })} /></label></div>
      {card && roomIndex >= 0 && mealIndex >= 0 ? <div className="package-structured__seasons"><strong>Room rates by season · per night</strong><div>{card.seasons.map((season, seasonIndex) => <span key={season.name}><small>{season.name} · {season.dates}</small><strong>{card.prices[roomIndex]?.[mealIndex]?.[seasonIndex] == null ? "Not quoted" : money.format(card.prices[roomIndex][mealIndex][seasonIndex]!)}</strong></span>)}</div><small>Final cost uses the reference check-in date, each night, weekends and applicable guest rules.</small></div> : null}
      {card ? <div className="package-structured__children"><div><strong>Children staying</strong><button type="button" onClick={() => onChange({ stayChildren: [...children, { age: -1, bed: false }] })}>+ Add child</button></div>{children.map((child, index) => <div className="package-structured__child" key={index}><label><span>Child {index + 1} age</span><input type="number" min="0" max="17" value={child.age < 0 ? "" : child.age} onChange={(event) => setChild(index, { age: event.target.value === "" ? -1 : Number(event.target.value) })} /></label><label><span>Bed</span><select value={child.bed ? "with" : "without"} onChange={(event) => setChild(index, { bed: event.target.value === "with" })}><option value="without">Without extra bed</option><option value="with">With extra bed</option></select></label><button type="button" aria-label={`Remove child ${index + 1}`} onClick={() => onChange({ stayChildren: children.filter((_, i) => i !== index) })}><Icon name="clear" size="xs" /></button></div>)}</div> : null}
      <p className="package-structured__hint">The check-in is a package pricing reference. A proposal uses the traveller's actual dates and recalculates seasonal rates.</p><CommonStatus service={service} onChange={onChange} /><Quote quote={quote} />
    </div>
  </section>;
}

function Transport({ service, dayIndex, onChange }: Props) {
  const card = availableTransportCards.find((item) => item.id === service.rateCardId);
  const mode = service.transportPricingMode ?? "transfer";
  const quote = serviceCostBreakdown(service, { dayIndex });
  const setAmount = (key: keyof ProposalService, value: string) => onChange({ [key]: number(value) });
  return <section className="package-structured" aria-label={`${service.title} transport costing`}>
    <header><span className="package-structured__icon"><Icon name="bus" size="sm" /></span><div><small>Day {dayIndex + 1} · Transport</small><h3>{service.title}</h3><span>{service.vendor ?? "Confirm the vehicle supplier"}</span></div><strong>{quote.status === "priced" ? money.format(quote.total) : quote.status === "included" ? "Included" : "Unpriced"}</strong></header>
    <div className="package-structured__body"><div className="package-structured__intro"><strong>Vehicle and route quote</strong><p>Choose the vehicle class, usable passenger seats, service standard and supplier rate. A larger or premium vehicle uses its own quoted rate; no price is inferred from its seats.</p></div>
      <div className="package-structured__grid"><label className="package-structured__wide"><span>Pricing source</span><select value={card?.id ?? "manual"} onChange={(event) => { const next = availableTransportCards.find((item) => item.id === event.target.value); onChange({ rateCardId: next?.id, vendor: next?.vendor ?? service.vendor, roomTypeId: next?.rooms[0]?.id, mealPlanCode: next?.meals[0]?.code, vehicleType: next?.meals[0]?.label ?? service.vehicleType, transportPricingMode: next ? undefined : mode, priceState: next ? "priced" : "unpriced", cost: undefined, vehicleCapacity: undefined }); }}><option value="manual">Confirmed supplier vehicle quote</option>{availableTransportCards.map((item) => <option value={item.id} key={item.id}>{item.vendor} · {item.name} · {item.validity}</option>)}</select></label>
      {card ? <><div className="package-structured__card-note"><strong>{card.ref}</strong><span>{card.validity} · {card.mealBasis}</span></div><label><span>Covered route</span><select value={service.roomTypeId ?? ""} onChange={(event) => onChange({ roomTypeId: event.target.value })}>{card.rooms.map((route) => <option value={route.id} key={route.id}>{route.name} · {route.note}</option>)}</select></label><label><span>Vehicle class</span><select value={service.mealPlanCode ?? ""} onChange={(event) => { const vehicle = card.meals.find((item) => item.code === event.target.value); onChange({ mealPlanCode: event.target.value, vehicleType: vehicle?.label, vehicleCapacity: undefined }); }}>{card.meals.map((vehicle) => <option value={vehicle.code} key={vehicle.code}>{vehicle.label}</option>)}</select></label></> : <><label><span>Supplier</span><input value={service.vendor ?? ""} onChange={(event) => onChange({ vendor: event.target.value })} placeholder="Vehicle supplier" /></label><label><span>Service pattern</span><select value={mode} onChange={(event) => onChange({ transportPricingMode: event.target.value as ProposalService["transportPricingMode"], cost: undefined, priceState: "unpriced" })}><option value="transfer">Point-to-point transfer</option><option value="local">Local vehicle by day</option><option value="outstation">Outstation by km</option></select></label><label><span>Vehicle class</span><select value={service.vehicleType ?? ""} onChange={(event) => onChange({ vehicleType: event.target.value, vehicleCapacity: undefined, cost: undefined, priceState: "unpriced" })}><option value="">Choose class</option><option>Sedan</option><option>SUV</option><option>MPV</option><option>Van / Tempo Traveller</option><option>Coach</option><option>Other</option></select></label><label><span>Service standard</span><select value={service.vehicleTier ?? "standard"} onChange={(event) => onChange({ vehicleTier: event.target.value as ProposalService["vehicleTier"], cost: undefined, priceState: "unpriced" })}><option value="standard">Standard / regular</option><option value="premium">Premium</option><option value="luxury">Luxury</option></select></label><label><span>{mode === "outstation" ? "Supplier rate per km (₹)" : mode === "local" ? "Rate per vehicle day (₹)" : "Rate per vehicle trip (₹)"}</span><input type="number" min="0" value={service.cost ?? ""} onChange={(event) => setAmount("cost", event.target.value)} placeholder="Rate for this exact class" /></label><label><span>From</span><input value={service.routeFrom ?? ""} onChange={(event) => onChange({ routeFrom: event.target.value })} placeholder="Pickup / origin" /></label><label><span>To</span><input value={service.routeTo ?? ""} onChange={(event) => onChange({ routeTo: event.target.value })} placeholder="Drop-off / destination" /></label></>}
      <label><span>Usable passenger seats / vehicle</span><input type="number" min="1" value={service.vehicleCapacity ?? ""} onChange={(event) => setAmount("vehicleCapacity", event.target.value)} placeholder="Exclude driver and luggage space" /></label><label><span>Number of vehicles</span><input type="number" min="1" value={service.quantity ?? 1} onChange={(event) => setAmount("quantity", event.target.value)} /></label><label><span>{card || mode === "transfer" ? "Trips / legs" : "Service days"}</span><input type="number" min="1" value={service.transportUnits ?? 1} onChange={(event) => setAmount("transportUnits", event.target.value)} /></label><label><span>Pricing reference date</span><input type="date" value={service.serviceDate ?? ""} onChange={(event) => onChange({ serviceDate: event.target.value })} /></label></div>
      {card ? <div className="package-structured__seasons"><strong>Published vehicle rates · per trip</strong><div>{card.meals.map((vehicle, index) => <span key={vehicle.code}><small>{vehicle.label} · {card.rooms.find((route) => route.id === service.roomTypeId)?.name ?? card.rooms[0]?.name}</small><strong>{money.format(card.prices[card.rooms.findIndex((route) => route.id === service.roomTypeId) >= 0 ? card.rooms.findIndex((route) => route.id === service.roomTypeId) : 0]?.[index]?.[0] ?? 0)}</strong></span>)}</div></div> : <div className="package-structured__extras"><strong>Distance and time rules</strong><div className="package-structured__grid">{mode === "outstation" ? <><label><span>Planned billable km</span><input type="number" min="0" value={service.plannedKm ?? ""} onChange={(event) => setAmount("plannedKm", event.target.value)} /></label><label><span>Minimum billable km / day</span><input type="number" min="0" value={service.minimumKmPerDay ?? ""} onChange={(event) => setAmount("minimumKmPerDay", event.target.value)} placeholder="0 if none" /></label></> : <><label><span>Planned km · all {mode === "local" ? "days" : "trips"}</span><input type="number" min="0" value={service.plannedKm ?? ""} onChange={(event) => setAmount("plannedKm", event.target.value)} placeholder={mode === "local" ? "Required" : "If distance capped"} /></label><label><span>Included km / {mode === "local" ? "day" : "trip"}</span><input type="number" min="0" value={service.includedKm ?? ""} onChange={(event) => setAmount("includedKm", event.target.value)} /></label><label><span>Extra rate / km (₹)</span><input type="number" min="0" value={service.extraKmRate ?? ""} onChange={(event) => setAmount("extraKmRate", event.target.value)} /></label><label><span>Planned hours · all {mode === "local" ? "days" : "trips"}</span><input type="number" min="0" value={service.plannedHours ?? ""} onChange={(event) => setAmount("plannedHours", event.target.value)} placeholder={mode === "local" ? "Required" : "If time capped"} /></label><label><span>Included hours / {mode === "local" ? "day" : "trip"}</span><input type="number" min="0" value={service.includedHours ?? ""} onChange={(event) => setAmount("includedHours", event.target.value)} /></label><label><span>Extra rate / hour (₹)</span><input type="number" min="0" value={service.extraHourRate ?? ""} onChange={(event) => setAmount("extraHourRate", event.target.value)} /></label></>}</div></div>}
      {card ? <div className="package-structured__extras"><strong>Card extras</strong><div className="package-structured__grid"><label><span>Waiting hours beyond included time</span><input type="number" min="0" value={service.waitingHours ?? 0} onChange={(event) => setAmount("waitingHours", event.target.value)} /></label><label><span>Tolls · trip total (₹)</span><input type="number" min="0" value={service.tolls ?? 0} onChange={(event) => setAmount("tolls", event.target.value)} /></label><label><span>Parking · trip total (₹)</span><input type="number" min="0" value={service.parking ?? 0} onChange={(event) => setAmount("parking", event.target.value)} /></label></div></div> : <div className="package-structured__extras"><strong>Driver and trip charges</strong><div className="package-structured__grid"><label><span>Driver allowance</span><select value={service.driverIncluded === false ? "extra" : "included"} onChange={(event) => onChange({ driverIncluded: event.target.value === "included" })}><option value="included">Included in supplier rate</option><option value="extra">Charged separately</option></select></label>{service.driverIncluded === false ? <label><span>Allowance / vehicle / trip or day (₹)</span><input type="number" min="0" value={service.driverAllowance ?? ""} onChange={(event) => setAmount("driverAllowance", event.target.value)} /></label> : null}<label><span>Tolls, parking, permits and supplier tax</span><select value={service.transportChargesStatus ?? "to_confirm"} onChange={(event) => onChange({ transportChargesStatus: event.target.value as ProposalService["transportChargesStatus"] })}><option value="to_confirm">To confirm</option><option value="included">Included in rate</option><option value="entered">Enter confirmed amounts</option></select></label>{service.transportChargesStatus === "entered" ? <>{([["Tolls", "tolls"], ["Parking", "parking"], ["Permits", "permitFees"], ["Supplier tax", "supplierTax"]] as const).map(([label, key]) => <label key={key}><span>{label} · trip total (₹)</span><input type="number" min="0" value={service[key] ?? ""} onChange={(event) => setAmount(key, event.target.value)} /></label>)}</> : null}</div></div>}
      <p className="package-structured__hint">Confirm usable seats with luggage for the actual vehicle. Changing class or standard needs a new supplier rate; the rate is never scaled from seat count.</p><CommonStatus service={service} onChange={onChange} /><Quote quote={quote} />
    </div>
  </section>;
}

export function PackageStructuredPricing(props: Props) {
  return props.service.serviceCategory === "Accommodation" ? <Accommodation {...props} /> : <Transport {...props} />;
}
