import { useState } from "react";
import type { ProposalService } from "./proposalModel";
import { availablePrivateTransportCards, privateTransportQuoteForService, serviceCostBreakdown } from "./serviceCosting";
import { initialPrivateTransportTrip, localPackageOptions, resolvePrivateTransportDays, suggestVehicleArrangements, TRANSPORT_TEMPLATE_LABELS, type PrivateTransportTrip } from "./modules/vendors/rateCard/privateTransport";
import { findPrivateTransportOptions } from "./modules/vendors/rateCard/transportOptions";
import { readVehicleOfferings } from "./modules/vendors/data/vehicleOfferings";
import { readSupplierTaxProfiles } from "./modules/vendors/rateCard/supplierTax";
import "./PrivateTransportProposalCosting.css";

const money = (amount: number | null | undefined) => amount == null ? "Pending" : new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(amount);
type Props = { service: ProposalService; dayIndex: number; groupTravellers?: number; retainedHire?: boolean; onChange: (patch: Partial<ProposalService>) => void };

export function PrivateTransportProposalCosting({ service, dayIndex, groupTravellers, retainedHire = false, onChange }: Props) {
  const [manualPackage, setManualPackage] = useState(false);
  const cards = availablePrivateTransportCards();
  const card = cards.find((item) => item.id === service.rateCardId);
  const tariff = card?.privateTransport;
  const offerings = readVehicleOfferings();
  const vehicles = offerings.filter((vehicle) => tariff?.vehicleIds.includes(vehicle.id) && vehicle.vendorId === tariff.vendorId && vehicle.serviceIds.includes(tariff.serviceId));
  const input = service.privateTransportInput ?? (tariff ? initialPrivateTransportTrip(tariff, service.serviceDate ?? "") : undefined);
  const requirement = input && service.transportCoversEntireGroup && groupTravellers ? { ...input, travellers: groupTravellers } : input;
  const set = (patch: Partial<PrivateTransportTrip>) => {
    if (!input) return;
    const next = { ...input, ...patch };
    if (Object.hasOwn(patch, "date") && input.endDate === input.date) next.endDate = patch.date;
    if (tariff?.template === "local-package" && !manualPackage && !Object.hasOwn(patch, "packageId")) next.packageId = localPackageOptions(tariff, next)[0]?.id ?? next.packageId;
    onChange({ privateTransportInput: next, privateTransportSnapshot: undefined, priceState: "unpriced" });
  };
  const setNumber = (key: keyof PrivateTransportTrip, value: string) => set({ [key]: Number(value) });
  const selectedRoute = tariff?.routes.find((route) => route.id === input?.routeId);
  const allocations = input?.vehicleAllocations ?? [];
  const suggestions = tariff && requirement ? suggestVehicleArrangements(vehicles, requirement) : [];
  const packages = tariff && requirement ? localPackageOptions(tariff, requirement) : [];
  const quote = serviceCostBreakdown(service, { dayIndex, travellers: groupTravellers });
  const calculation = privateTransportQuoteForService(service, { dayIndex, travellers: groupTravellers })?.result;
  const matching = requirement ? findPrivateTransportOptions(cards.map((item) => ({ id: item.id, name: item.name, vendor: item.vendor, tariff: item.privateTransport! })), offerings, requirement, readSupplierTaxProfiles()) : [];
  const hireIdFor = (nextTariff: typeof tariff) => nextTariff?.template === "outstation-km" || nextTariff?.template === "daily-hire" ? service.transportHireId ?? `hire-${Date.now()}` : undefined;
  const selectCard = (id: string) => {
    if (id === "manual") { onChange({ rateCardId: undefined, privateTransportInput: undefined, privateTransportSnapshot: undefined, transportHireId: undefined, priceState: "unpriced" }); return; }
    const next = cards.find((item) => item.id === id);
    if (!next?.privateTransport) return;
    const base = input ?? initialPrivateTransportTrip(next.privateTransport);
    const route = next.privateTransport.routes.find((item) => item.from.toLowerCase() === base.pickup.toLowerCase() && item.to.toLowerCase() === base.drop.toLowerCase());
    const nextInput = { ...base, routeId: route?.id ?? "", packageId: next.privateTransport.packages[0]?.id ?? "", vehicleId: next.privateTransport.vehicleIds[0] ?? "", vehicleAllocations: next.privateTransport.vehicleIds[0] ? [{ vehicleId: next.privateTransport.vehicleIds[0], quantity: 1 }] : [] };
    onChange({ rateCardId: next.id, vendor: next.vendor, sourceId: next.privateTransport.serviceId, sourceVendorId: next.privateTransport.vendorId, privateTransportInput: nextInput, privateTransportSnapshot: undefined, transportHireId: hireIdFor(next.privateTransport), priceState: "unpriced" });
  };
  return <section className="private-proposal" aria-label="Private transport supplier costing">
    <header><div><small>Day {dayIndex + 1} · Private transport</small><h3>{service.title}</h3><span>{card?.vendor ?? "Choose a transport supplier"}</span></div><strong>{quote.status === "priced" ? money(quote.total) : calculation?.quoteBasis === "base-plus-actuals" ? `${money(calculation.commercialAmount)} + actuals` : "To confirm"}</strong></header>
    <div className="private-proposal__body">
      <label className="private-proposal__full"><span>Vendor rate card</span><select value={card?.id ?? ""} onChange={(event) => selectCard(event.target.value)}><option value="">Choose a supplier tariff</option>{cards.filter((item) => !tariff || item.privateTransport?.template === tariff.template).map((item) => <option value={item.id} key={item.id}>{item.vendor} · {item.name} · {TRANSPORT_TEMPLATE_LABELS[item.privateTransport!.template]}</option>)}<option value="manual">Manual supplier quote</option></select></label>
      {!tariff || !input ? <p className="private-proposal__hint">Select a vendor-owned rate card to check vehicles, the trip and supplier cost.</p> : <>
        <div className="private-proposal__label">{TRANSPORT_TEMPLATE_LABELS[tariff.template]} · {tariff.validFrom} to {tariff.validTo} · {card?.ref}</div>
        {tariff.template === "outstation-km" || tariff.template === "daily-hire" ? <label className="private-proposal__full"><span>Continuous hire reference</span><input value={service.transportHireId ?? ""} onChange={(event) => onChange({ transportHireId: event.target.value.trim() || undefined })} placeholder="Use the same reference when this hire appears on several itinerary days" /></label> : null}
        {retainedHire ? <p className="private-proposal__hint">This day references a vehicle hire already costed elsewhere in the itinerary. Keep the tariff and trip details identical to count it once.</p> : null}
        <div className="private-proposal__grid">
          <label><span>Service date</span><input type="date" value={input.date} onChange={(event) => set({ date: event.target.value })} /></label>
          <label><span>Pickup time</span><input type="time" value={input.pickupTime} onChange={(event) => set({ pickupTime: event.target.value })} /></label>
          {tariff.template === "fixed-transfer" ? <label className="private-proposal__full"><span>Supplier route</span><select value={selectedRoute?.id ?? ""} onChange={(event) => { const route = tariff.routes.find((item) => item.id === event.target.value); if (route) set({ routeId: route.id, pickup: route.from, drop: route.to }); }}><option value="">Choose covered direction</option>{tariff.routes.map((route) => <option value={route.id} key={route.id}>{route.from} → {route.to}</option>)}</select></label> : <><label><span>Pickup</span><input value={input.pickup} onChange={(event) => set({ pickup: event.target.value })} /></label><label><span>Final drop</span><input value={input.drop} onChange={(event) => set({ drop: event.target.value })} /></label></>}
          {groupTravellers ? <label><span>Travellers covered</span><select value={service.transportCoversEntireGroup ? "all" : "selected"} onChange={(event) => onChange({ transportCoversEntireGroup: event.target.value === "all", privateTransportSnapshot: undefined })}><option value="all">Entire proposal group</option><option value="selected">Selected travellers / split arrival</option></select></label> : null}
          <label><span>Customers requiring seats</span><input type="number" min="1" value={requirement?.travellers ?? input.travellers} readOnly={Boolean(service.transportCoversEntireGroup && groupTravellers)} onChange={(event) => setNumber("travellers", event.target.value)} /></label>
          <label><span>Guide / staff seats</span><input type="number" min="0" value={input.guideSeats} onChange={(event) => setNumber("guideSeats", event.target.value)} /></label>
          <label><span>Medium bags</span><input type="number" min="0" value={input.mediumBags} onChange={(event) => setNumber("mediumBags", event.target.value)} /></label>
          <label><span>Large suitcases</span><input type="number" min="0" value={input.largeBags ?? 0} onChange={(event) => setNumber("largeBags", event.target.value)} /></label>
          <label><span>Cabin bags</span><input type="number" min="0" value={input.cabinBags ?? 0} onChange={(event) => setNumber("cabinBags", event.target.value)} /></label>
          <label><span>Air conditioning</span><select value={input.acRequired ? "required" : "any"} onChange={(event) => set({ acRequired: event.target.value === "required" })}><option value="required">Required</option><option value="any">Any</option></select></label>
          {tariff.template === "local-package" ? <label><span>Supplier package</span><select value={input.packageId} onChange={(event) => { setManualPackage(true); set({ packageId: event.target.value }); }}>{packages.map((pkg) => <option key={pkg.id} value={pkg.id}>{pkg.name} · {money(pkg.amount)}</option>)}</select></label> : null}
          {tariff.template !== "fixed-transfer" ? <label><span>Planned kilometres</span><input type="number" min="0" value={input.plannedKm} onChange={(event) => setNumber("plannedKm", event.target.value)} /></label> : cards.some((item) => item.privateTransport?.template === "outstation-km") ? <label><span>Planned kilometres for alternative tariff comparison</span><input type="number" min="0" value={input.plannedKm || ""} placeholder="Optional; fixed fare stays unchanged" onChange={(event) => setNumber("plannedKm", event.target.value)} /></label> : null}
          {tariff.template === "local-package" || tariff.template === "daily-hire" ? <label><span>Planned hours</span><input type="number" min="0" value={input.plannedHours} onChange={(event) => setNumber("plannedHours", event.target.value)} /></label> : null}
          {tariff.template === "outstation-km" || tariff.template === "daily-hire" || tariff.template === "fixed-transfer" && input.plannedKm > 0 ? <><label><span>Final service date</span><input type="date" value={input.endDate ?? ""} onChange={(event) => set({ endDate: event.target.value })} /></label><label><span>Final drop time</span><input type="time" value={input.dropTime ?? ""} onChange={(event) => set({ dropTime: event.target.value })} /></label></> : null}
          {tariff.charges.some((charge) => charge.trigger === "waiting-over") ? <label><span>Waiting minutes</span><input type="number" min="0" value={input.waitingMinutes} onChange={(event) => setNumber("waitingMinutes", event.target.value)} /></label> : null}
        </div>
        {tariff.template === "outstation-km" || tariff.template === "daily-hire" ? <div className="private-proposal__days"><strong>{resolvePrivateTransportDays(tariff, input) == null ? "Set final date and time" : `${resolvePrivateTransportDays(tariff, input)} billable ${resolvePrivateTransportDays(tariff, input) === 1 ? "day" : "days"}`}</strong>{Array.from({ length: Math.min(31, resolvePrivateTransportDays(tariff, input) ?? 0) }, (_, index) => <div key={index}><span>Day {index + 1}</span><label>Km<input type="number" min="0" value={input.dailyKm[index] ?? ""} onChange={(event) => set({ dailyKm: Array.from({ length: resolvePrivateTransportDays(tariff, input) ?? 0 }, (_, day) => day === index ? Number(event.target.value) : input.dailyKm[day] ?? 0) })} /></label>{tariff.template === "daily-hire" ? <label>Hours<input type="number" min="0" value={input.dailyHours[index] ?? ""} onChange={(event) => set({ dailyHours: Array.from({ length: resolvePrivateTransportDays(tariff, input) ?? 0 }, (_, day) => day === index ? Number(event.target.value) : input.dailyHours[day] ?? 0) })} /></label> : null}</div>)}</div> : null}
        <div className="private-proposal__fleet"><strong>Vehicle arrangement</strong><div className="private-proposal__suggestions">{suggestions.slice(0, 8).map((rows) => <button type="button" key={rows.map((row) => `${row.vehicleId}-${row.quantity}`).join("+")} onClick={() => set({ vehicleAllocations: rows, vehicleId: rows[0].vehicleId, vehicleCount: rows[0].quantity })}>{rows.map((row) => `${row.quantity} ${vehicles.find((vehicle) => vehicle.id === row.vehicleId)?.label ?? "vehicle"}`).join(" + ")}</button>)}</div>{!suggestions.length ? <small>No confirmed vehicle offering fits the entered seats and bags.</small> : null}{allocations.map((row, index) => <div className="private-proposal__fleet-row" key={index}><select aria-label={`Vehicle ${index + 1}`} value={row.vehicleId} onChange={(event) => set({ vehicleAllocations: allocations.map((item, position) => position === index ? { ...item, vehicleId: event.target.value } : item) })}>{vehicles.map((vehicle) => <option value={vehicle.id} key={vehicle.id}>{vehicle.label} · {vehicle.passengerSeats} seats · {vehicle.largeBags ?? "?"} large bags</option>)}</select><input aria-label={`Quantity for vehicle ${index + 1}`} type="number" min="1" value={row.quantity} onChange={(event) => set({ vehicleAllocations: allocations.map((item, position) => position === index ? { ...item, quantity: Number(event.target.value) } : item) })} /><button type="button" onClick={() => set({ vehicleAllocations: allocations.filter((_, position) => position !== index) })}>Remove</button></div>)}<button type="button" onClick={() => set({ vehicleAllocations: [...allocations, { vehicleId: vehicles[0]?.id ?? "", quantity: 1 }] })}>+ Add vehicle</button></div>
        {matching.some((option) => option.id !== card?.id) ? <div className="private-proposal__matching"><strong>Other eligible supplier tariffs</strong>{matching.filter((option) => option.id !== card?.id).map((option) => <button type="button" key={option.id} onClick={() => onChange({ rateCardId: option.id, vendor: option.vendor, sourceId: option.tariff.serviceId, sourceVendorId: option.tariff.vendorId, privateTransportInput: option.input, privateTransportSnapshot: undefined, transportHireId: hireIdFor(option.tariff), priceState: "unpriced" })}><span>{option.vendor} · {TRANSPORT_TEMPLATE_LABELS[option.tariff.template]} · {option.name}</span><strong>{money(option.quote.commercialAmount)}{option.quote.actualCharges.length ? " + actuals" : ""}</strong></button>)}</div> : null}
        {calculation?.actualCharges.length ? <label className="private-proposal__full"><span>Payable-at-actuals terms</span><select value={service.transportActualsTerm ?? ""} onChange={(event) => onChange({ transportActualsTerm: event.target.value ? event.target.value as ProposalService["transportActualsTerm"] : undefined, privateTransportSnapshot: undefined })}><option value="">Choose how actuals are handled</option><option value="agency-absorbs">Agency absorbs actuals within the customer quote</option><option value="customer-pays">Customer pays actuals separately from the displayed price</option></select></label> : null}
        <div className="private-proposal__quote"><strong>Supplier calculation</strong>{calculation?.vehicleLines?.map((line) => <div key={line.vehicleId}><span>{line.quantity} × {vehicles.find((vehicle) => vehicle.id === line.vehicleId)?.label ?? "vehicle"}</span><b>{line.base == null || line.driver == null || line.excess == null || line.fixedExtras == null ? "Pending" : money(line.base + line.driver + line.excess + line.fixedExtras)}</b></div>)}{calculation?.billableKm != null ? <p>Billable distance: {calculation.billableKm} km. Planned: {input.plannedKm} km.</p> : null}<div><span>Base vehicle tariff</span><b>{money(calculation?.base)}</b></div><div><span>Driver allowance</span><b>{money(calculation?.driver)}</b></div><div><span>Excess usage</span><b>{money(calculation?.excess)}</b></div><div><span>Fixed additional charges</span><b>{money(calculation?.fixedExtras)}</b></div><div><span>Supplier tax</span><b>{calculation?.supplierTax == null ? tariff.taxMode === "inclusive" ? "Included; breakdown pending profile" : "Pending approved profile" : money(calculation.supplierTax)}</b></div><div className="private-proposal__payable"><span>Supplier payable</span><b>{money(calculation?.supplierPayable)}</b></div>{calculation?.actualCharges.length ? <p>{calculation.commercialAmount == null ? "Actual charges are recorded, but trip details still need a valid base calculation." : `Known supplier amount: ${money(calculation.commercialAmount)} plus ${calculation.actualCharges.join(", ")} at actuals. The final payable remains open until those amounts are confirmed.`}</p> : null}{calculation?.blockers.length ? <ul>{calculation.blockers.map((message) => <li key={message}>{message}</li>)}</ul> : null}{quote.issue && !calculation?.blockers.includes(quote.issue) ? <p>{quote.issue}</p> : null}</div>
        <p className="private-proposal__hint">A valid tariff is a costing source. Vehicle availability and supplier confirmation are handled in Booking.</p>
      </>}
    </div>
  </section>;
}
